// Generated by CIRCT firtool-1.62.0
module Addr1(	// src/main/scala/componets/EX/Addr.scala:6:7
  input  io_A,	// src/main/scala/componets/EX/Addr.scala:7:16
         io_B,	// src/main/scala/componets/EX/Addr.scala:7:16
         io_Cin,	// src/main/scala/componets/EX/Addr.scala:7:16
  output io_Result,	// src/main/scala/componets/EX/Addr.scala:7:16
         io_Carry	// src/main/scala/componets/EX/Addr.scala:7:16
);

  wire G = io_A & io_B;	// src/main/scala/componets/EX/Addr.scala:15:17
  assign io_Result = io_A ^ io_B ^ io_Cin;	// src/main/scala/componets/EX/Addr.scala:6:7, :23:27
  assign io_Carry = G | ~G & (io_A | io_B) & io_Cin;	// src/main/scala/componets/EX/Addr.scala:6:7, :15:17, :16:17, :20:{18,20,22}
endmodule

