// Generated by CIRCT firtool-1.62.0
module Alu(	// src/main/scala/componets/EX/Alu.scala:7:7
  input  [3:0]  io_AluControl,	// src/main/scala/componets/EX/Alu.scala:8:16
  input  [31:0] io_DataIn1,	// src/main/scala/componets/EX/Alu.scala:8:16
                io_DataIn2,	// src/main/scala/componets/EX/Alu.scala:8:16
  output [31:0] io_DataOut,	// src/main/scala/componets/EX/Alu.scala:8:16
  output        io_Zero	// src/main/scala/componets/EX/Alu.scala:8:16
);

  wire [31:0] _adder_io_Result;	// src/main/scala/componets/EX/Alu.scala:17:23
  wire        _adder_io_Zero;	// src/main/scala/componets/EX/Alu.scala:17:23
  wire        _adder_io_OF;	// src/main/scala/componets/EX/Alu.scala:17:23
  wire        _adder_io_CF;	// src/main/scala/componets/EX/Alu.scala:17:23
  /* verilator lint_off UNUSEDSIGNAL */
  wire [62:0] _resultVec_6_T_1 = {31'h0, io_DataIn1} << io_DataIn2[4:0];	// src/main/scala/componets/EX/Alu.scala:27:18, :37:{33,46}
  wire [31:0] _GEN = {27'h0, io_DataIn2[4:0]};	// src/main/scala/componets/EX/Alu.scala:37:46, :38:33
  CarryBypassAdder adder (	// src/main/scala/componets/EX/Alu.scala:17:23
    .io_A      (io_DataIn1),
    .io_B      (io_DataIn2),
    .io_Cin    (io_AluControl[0]),	// src/main/scala/componets/EX/Alu.scala:20:34
    .io_Result (_adder_io_Result),
    .io_Zero   (_adder_io_Zero),
    .io_OF     (_adder_io_OF),
    .io_CF     (_adder_io_CF)
  );
  assign io_DataOut =
    io_AluControl == 4'h0 | io_AluControl == 4'h1
      ? _adder_io_Result
      : io_AluControl == 4'h3
          ? {31'h0, (_adder_io_Result[31] ^ _adder_io_OF) & ~_adder_io_Zero}
          : io_AluControl == 4'h5
              ? {31'h0, _adder_io_CF}
              : io_AluControl == 4'h8
                  ? io_DataIn1 & io_DataIn2
                  : io_AluControl == 4'h6
                      ? io_DataIn1 | io_DataIn2
                      : io_AluControl == 4'h4
                          ? io_DataIn1 ^ io_DataIn2
                          : io_AluControl == 4'hA
                              ? _resultVec_6_T_1[31:0]
                              : io_AluControl == 4'hC
                                  ? io_DataIn1 >> _GEN
                                  : io_AluControl == 4'hE
                                      ? $signed($signed(io_DataIn1) >>> _GEN)
                                      : 32'h0;	// src/main/scala/componets/EX/Alu.scala:7:7, :17:23, :27:{18,37,41,54,56}, :29:18, :32:32, :33:32, :34:32, :37:{18,33}, :38:33, :39:40, :42:16, :44:26, :45:36, :46:36, :47:36, :48:37, :49:36, :50:35, :51:36, :52:36, :53:36, :54:36
  assign io_Zero = _adder_io_Zero;	// src/main/scala/componets/EX/Alu.scala:7:7, :17:23
endmodule

