// Generated by CIRCT firtool-1.62.0
module BranchRedirectUnit(	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:16:7
  input         io_in_bru_out_jmp_valid,	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:17:16
  input  [31:0] io_in_bru_out_jmp_pc,	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:17:16
  output        io_out_redirect_valid,	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:17:16
  output [31:0] io_out_redirect_target	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:17:16
);

  assign io_out_redirect_valid = io_in_bru_out_jmp_valid;	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:16:7
  assign io_out_redirect_target = io_in_bru_out_jmp_pc;	// src/main/scala/componets/HAZARD/BranchRedirectUnit.scala:16:7
endmodule

