// Generated by CIRCT firtool-1.62.0
module BRU(	// src/main/scala/componets/EX/bru.scala:23:7
  input         io_in1_is_less,	// src/main/scala/componets/EX/bru.scala:24:16
                io_in1_is_zero,	// src/main/scala/componets/EX/bru.scala:24:16
  input  [3:0]  io_in1_jmp_code,	// src/main/scala/componets/EX/bru.scala:24:16
  input         io_in1_halt_jmp,	// src/main/scala/componets/EX/bru.scala:24:16
  input  [31:0] io_in1_halt_pc,	// src/main/scala/componets/EX/bru.scala:24:16
                io_in1_cur_pc,	// src/main/scala/componets/EX/bru.scala:24:16
                io_in1_imm,	// src/main/scala/componets/EX/bru.scala:24:16
                io_in1_reg_src1,	// src/main/scala/componets/EX/bru.scala:24:16
  output        io_out_jmp_valid,	// src/main/scala/componets/EX/bru.scala:24:16
  output [31:0] io_out_jmp_pc	// src/main/scala/componets/EX/bru.scala:24:16
);

  wire [31:0] _pcSrc_T_2 =
    (io_in1_jmp_code == 4'h2 ? io_in1_reg_src1 : io_in1_cur_pc) + io_in1_imm;	// src/main/scala/componets/EX/bru.scala:29:37, :36:{17,66}
  wire [5:0]  J_B_control = {io_in1_is_zero, io_in1_is_less, io_in1_jmp_code};	// src/main/scala/componets/EX/bru.scala:39:26
  wire        _J_B_valid_T_1 = J_B_control == 6'h31;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_2 = J_B_control == 6'h21;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_4 = J_B_control == 6'h11;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_6 = J_B_control == 6'h1;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_8 = J_B_control == 6'h32;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_10 = J_B_control == 6'h22;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_12 = J_B_control == 6'h12;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_14 = J_B_control == 6'h2;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_16 = J_B_control == 6'h23;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_18 = J_B_control == 6'h33;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_20 = J_B_control == 6'h4;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_22 = J_B_control == 6'h14;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_24 = J_B_control == 6'h15;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_26 = J_B_control == 6'h6;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_28 = J_B_control == 6'h26;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_30 = J_B_control == 6'h17;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_32 = J_B_control == 6'h8;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  wire        _J_B_valid_T_34 = J_B_control == 6'h28;	// src/main/scala/componets/EX/bru.scala:39:26, :41:48
  assign io_out_jmp_valid =
    _J_B_valid_T_34 | _J_B_valid_T_32 | _J_B_valid_T_30 | _J_B_valid_T_28
    | _J_B_valid_T_26 | _J_B_valid_T_24 | _J_B_valid_T_22 | _J_B_valid_T_20
    | _J_B_valid_T_18 | _J_B_valid_T_16 | _J_B_valid_T_14 | _J_B_valid_T_12
    | _J_B_valid_T_10 | _J_B_valid_T_8 | _J_B_valid_T_6 | _J_B_valid_T_4 | _J_B_valid_T_2
    | _J_B_valid_T_1 | io_in1_halt_jmp;	// src/main/scala/componets/EX/bru.scala:23:7, :41:48, :83:35
  assign io_out_jmp_pc =
    io_in1_halt_jmp
      ? io_in1_halt_pc
      : _J_B_valid_T_34 | _J_B_valid_T_32 | _J_B_valid_T_30 | _J_B_valid_T_28
        | _J_B_valid_T_26 | _J_B_valid_T_24 | _J_B_valid_T_22 | _J_B_valid_T_20
        | _J_B_valid_T_18 | _J_B_valid_T_16
          ? _pcSrc_T_2
          : _J_B_valid_T_14 | _J_B_valid_T_12 | _J_B_valid_T_10 | _J_B_valid_T_8
              ? {_pcSrc_T_2[31:1], 1'h0}
              : _J_B_valid_T_6 | _J_B_valid_T_4 | _J_B_valid_T_2 | _J_B_valid_T_1
                  ? _pcSrc_T_2
                  : 32'h0;	// src/main/scala/componets/EX/bru.scala:23:7, :29:19, :36:66, :37:{22,28}, :41:48, :82:25
endmodule

