// Generated by CIRCT firtool-1.62.0
module CarryBypassAdderUnit(	// src/main/scala/componets/EX/Addr.scala:25:7
  input  [3:0] io_A,	// src/main/scala/componets/EX/Addr.scala:26:16
               io_B,	// src/main/scala/componets/EX/Addr.scala:26:16
  input        io_Cin,	// src/main/scala/componets/EX/Addr.scala:26:16
  output [3:0] io_Result,	// src/main/scala/componets/EX/Addr.scala:26:16
  output       io_Carry	// src/main/scala/componets/EX/Addr.scala:26:16
);

  wire _addr4_4_io_Result;	// src/main/scala/componets/EX/Addr.scala:38:25
  wire _addr4_3_io_Result;	// src/main/scala/componets/EX/Addr.scala:37:25
  wire _addr4_3_io_Carry;	// src/main/scala/componets/EX/Addr.scala:37:25
  wire _addr4_2_io_Result;	// src/main/scala/componets/EX/Addr.scala:36:25
  wire _addr4_2_io_Carry;	// src/main/scala/componets/EX/Addr.scala:36:25
  wire _addr4_1_io_Result;	// src/main/scala/componets/EX/Addr.scala:35:25
  wire _addr4_1_io_Carry;	// src/main/scala/componets/EX/Addr.scala:35:25
  Addr1 addr4_1 (	// src/main/scala/componets/EX/Addr.scala:35:25
    .io_A      (io_A[0]),	// src/main/scala/componets/EX/Addr.scala:42:25
    .io_B      (io_B[0]),	// src/main/scala/componets/EX/Addr.scala:43:25
    .io_Cin    (io_Cin),
    .io_Result (_addr4_1_io_Result),
    .io_Carry  (_addr4_1_io_Carry)
  );
  Addr1 addr4_2 (	// src/main/scala/componets/EX/Addr.scala:36:25
    .io_A      (io_A[1]),	// src/main/scala/componets/EX/Addr.scala:47:25
    .io_B      (io_B[1]),	// src/main/scala/componets/EX/Addr.scala:48:25
    .io_Cin    (_addr4_1_io_Carry),	// src/main/scala/componets/EX/Addr.scala:35:25
    .io_Result (_addr4_2_io_Result),
    .io_Carry  (_addr4_2_io_Carry)
  );
  Addr1 addr4_3 (	// src/main/scala/componets/EX/Addr.scala:37:25
    .io_A      (io_A[2]),	// src/main/scala/componets/EX/Addr.scala:52:25
    .io_B      (io_B[2]),	// src/main/scala/componets/EX/Addr.scala:53:25
    .io_Cin    (_addr4_2_io_Carry),	// src/main/scala/componets/EX/Addr.scala:36:25
    .io_Result (_addr4_3_io_Result),
    .io_Carry  (_addr4_3_io_Carry)
  );
  Addr1 addr4_4 (	// src/main/scala/componets/EX/Addr.scala:38:25
    .io_A      (io_A[3]),	// src/main/scala/componets/EX/Addr.scala:57:25
    .io_B      (io_B[3]),	// src/main/scala/componets/EX/Addr.scala:58:25
    .io_Cin    (_addr4_3_io_Carry),	// src/main/scala/componets/EX/Addr.scala:37:25
    .io_Result (_addr4_4_io_Result),
    .io_Carry  (io_Carry)
  );
  assign io_Result =
    {_addr4_4_io_Result, _addr4_3_io_Result, _addr4_2_io_Result, _addr4_1_io_Result};	// src/main/scala/componets/EX/Addr.scala:25:7, :35:25, :36:25, :37:25, :38:25, :63:22
endmodule

