// Generated by CIRCT firtool-1.62.0
module CarryBypassAdder(	// src/main/scala/componets/EX/Addr.scala:67:7
  input  [31:0] io_A,	// src/main/scala/componets/EX/Addr.scala:68:16
                io_B,	// src/main/scala/componets/EX/Addr.scala:68:16
  input         io_Cin,	// src/main/scala/componets/EX/Addr.scala:68:16
  output [31:0] io_Result,	// src/main/scala/componets/EX/Addr.scala:68:16
  output        io_Zero,	// src/main/scala/componets/EX/Addr.scala:68:16
                io_OF,	// src/main/scala/componets/EX/Addr.scala:68:16
                io_CF	// src/main/scala/componets/EX/Addr.scala:68:16
);

  wire [3:0]  _CarryBypassAdderUnit_7_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_7_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_6_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_6_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_5_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_5_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_4_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_4_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_3_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_3_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_2_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_2_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_1_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_1_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [3:0]  _CarryBypassAdderUnit_io_Result;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire        _CarryBypassAdderUnit_io_Carry;	// src/main/scala/componets/EX/Addr.scala:87:45
  wire [31:0] B_comp = {32{io_Cin}} ^ io_B;	// src/main/scala/componets/EX/Addr.scala:81:{22,33}
  wire        cin_pass_0 =
    (io_A[0] ^ B_comp[0]) & (io_A[1] ^ B_comp[1]) & (io_A[2] ^ B_comp[2])
    & (io_A[3] ^ B_comp[3])
      ? io_Cin
      : _CarryBypassAdderUnit_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :97:27
  wire        cin_pass_1 =
    (io_A[4] ^ B_comp[4]) & (io_A[5] ^ B_comp[5]) & (io_A[6] ^ B_comp[6])
    & (io_A[7] ^ B_comp[7])
      ? cin_pass_0
      : _CarryBypassAdderUnit_1_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :97:27, :102:27
  wire        cin_pass_2 =
    (io_A[8] ^ B_comp[8]) & (io_A[9] ^ B_comp[9]) & (io_A[10] ^ B_comp[10])
    & (io_A[11] ^ B_comp[11])
      ? cin_pass_1
      : _CarryBypassAdderUnit_2_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :102:27
  wire        cin_pass_3 =
    (io_A[12] ^ B_comp[12]) & (io_A[13] ^ B_comp[13]) & (io_A[14] ^ B_comp[14])
    & (io_A[15] ^ B_comp[15])
      ? cin_pass_2
      : _CarryBypassAdderUnit_3_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :102:27
  wire        cin_pass_4 =
    (io_A[16] ^ B_comp[16]) & (io_A[17] ^ B_comp[17]) & (io_A[18] ^ B_comp[18])
    & (io_A[19] ^ B_comp[19])
      ? cin_pass_3
      : _CarryBypassAdderUnit_4_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :102:27
  wire        cin_pass_5 =
    (io_A[20] ^ B_comp[20]) & (io_A[21] ^ B_comp[21]) & (io_A[22] ^ B_comp[22])
    & (io_A[23] ^ B_comp[23])
      ? cin_pass_4
      : _CarryBypassAdderUnit_5_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :102:27
  wire        cin_pass_6 =
    (io_A[24] ^ B_comp[24]) & (io_A[25] ^ B_comp[25]) & (io_A[26] ^ B_comp[26])
    & (io_A[27] ^ B_comp[27])
      ? cin_pass_5
      : _CarryBypassAdderUnit_6_io_Carry;	// src/main/scala/componets/EX/Addr.scala:81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :102:27
  wire [31:0] io_Result_0 =
    {_CarryBypassAdderUnit_7_io_Result,
     _CarryBypassAdderUnit_6_io_Result,
     _CarryBypassAdderUnit_5_io_Result,
     _CarryBypassAdderUnit_4_io_Result,
     _CarryBypassAdderUnit_3_io_Result,
     _CarryBypassAdderUnit_2_io_Result,
     _CarryBypassAdderUnit_1_io_Result,
     _CarryBypassAdderUnit_io_Result};	// src/main/scala/componets/EX/Addr.scala:87:45, :106:21
  CarryBypassAdderUnit CarryBypassAdderUnit (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[3:0]),	// src/main/scala/componets/EX/Addr.scala:94:29
    .io_B      (B_comp[3:0]),	// src/main/scala/componets/EX/Addr.scala:81:33, :95:31
    .io_Cin    (io_Cin),
    .io_Result (_CarryBypassAdderUnit_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_1 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[7:4]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[7:4]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_0),	// src/main/scala/componets/EX/Addr.scala:97:27
    .io_Result (_CarryBypassAdderUnit_1_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_1_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_2 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[11:8]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[11:8]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_1),	// src/main/scala/componets/EX/Addr.scala:102:27
    .io_Result (_CarryBypassAdderUnit_2_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_2_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_3 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[15:12]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[15:12]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_2),	// src/main/scala/componets/EX/Addr.scala:102:27
    .io_Result (_CarryBypassAdderUnit_3_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_3_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_4 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[19:16]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[19:16]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_3),	// src/main/scala/componets/EX/Addr.scala:102:27
    .io_Result (_CarryBypassAdderUnit_4_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_4_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_5 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[23:20]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[23:20]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_4),	// src/main/scala/componets/EX/Addr.scala:102:27
    .io_Result (_CarryBypassAdderUnit_5_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_5_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_6 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[27:24]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[27:24]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_5),	// src/main/scala/componets/EX/Addr.scala:102:27
    .io_Result (_CarryBypassAdderUnit_6_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_6_io_Carry)
  );
  CarryBypassAdderUnit CarryBypassAdderUnit_7 (	// src/main/scala/componets/EX/Addr.scala:87:45
    .io_A      (io_A[31:28]),	// src/main/scala/componets/EX/Addr.scala:99:29
    .io_B      (B_comp[31:28]),	// src/main/scala/componets/EX/Addr.scala:81:33, :100:31
    .io_Cin    (cin_pass_6),	// src/main/scala/componets/EX/Addr.scala:102:27
    .io_Result (_CarryBypassAdderUnit_7_io_Result),
    .io_Carry  (_CarryBypassAdderUnit_7_io_Carry)
  );
  assign io_Result = io_Result_0;	// src/main/scala/componets/EX/Addr.scala:67:7, :106:21
  assign io_Zero = io_Result_0 == 32'h0;	// src/main/scala/componets/EX/Addr.scala:67:7, :81:22, :106:21, :108:27
  assign io_OF =
    io_A[31] == B_comp[31] & io_A[31] != _CarryBypassAdderUnit_7_io_Result[3];	// src/main/scala/componets/EX/Addr.scala:67:7, :81:33, :87:45, :91:{108,122}, :109:{23,37,48,60}
  assign io_CF =
    ((io_A[28] ^ B_comp[28]) & (io_A[29] ^ B_comp[29]) & (io_A[30] ^ B_comp[30])
     & (io_A[31] ^ B_comp[31])
       ? cin_pass_6
       : _CarryBypassAdderUnit_7_io_Carry) ^ io_Cin;	// src/main/scala/componets/EX/Addr.scala:67:7, :81:33, :87:45, :91:{28,33,40,52,59,66,80,87,94,102,108,115,122}, :102:27, :110:22
endmodule

