// Generated by CIRCT firtool-1.62.0
module cpu(	// src/main/scala/componets/core.scala:24:7
  input         clock,	// src/main/scala/componets/core.scala:24:7
                reset,	// src/main/scala/componets/core.scala:24:7
  output [31:0] io_debugPort_aluOutput,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_memOutput,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_instOutput,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_pcOutput,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_a0reg,	// src/main/scala/componets/core.scala:25:16
  output [5:0]  io_debugPort_pcControl,	// src/main/scala/componets/core.scala:25:16
  output [1:0]  io_debugPort_mem_code,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_mem_size,	// src/main/scala/componets/core.scala:25:16
  output        io_debugPort_rg_wen,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_is_csr_inst,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_is_load_inst,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_rg_we,	// src/main/scala/componets/core.scala:25:16
  output [2:0]  io_debugPort_control_reg_w_data,	// src/main/scala/componets/core.scala:25:16
  output [3:0]  io_debugPort_control_alu_code,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_jmp_code,	// src/main/scala/componets/core.scala:25:16
  output [1:0]  io_debugPort_control_mem_code,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_mem_size,	// src/main/scala/componets/core.scala:25:16
  output [2:0]  io_debugPort_control_sys_code,	// src/main/scala/componets/core.scala:25:16
  output [1:0]  io_debugPort_control_sys_src1,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_rs1_src,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_rs2_src,	// src/main/scala/componets/core.scala:25:16
  output        io_debugPort_control_mem_en,	// src/main/scala/componets/core.scala:25:16
  output [2:0]  io_debugPort_control_imm_type,	// src/main/scala/componets/core.scala:25:16
  output [4:0]  io_debugPort_control_rs1,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_rs2,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_control_rd,	// src/main/scala/componets/core.scala:25:16
  output [11:0] io_debugPort_control_csr_wad,	// src/main/scala/componets/core.scala:25:16
  output        io_debugPort_jmp_valid,	// src/main/scala/componets/core.scala:25:16
                io_debugPort_is_hazard,	// src/main/scala/componets/core.scala:25:16

  //---------------------------------将dmem和cpu主体部分分离-------------------------------------
  output wire  [31:0] Addr_cpu,
  output wire  [31:0] WD_cpu,
  output wire         WE_cpu,
  output wire  [1:0]  LEN_cpu,
  input        [31:0] dout_cpu
  //--------------------------------------------------------------------------------------------
);

  wire        _branchRedirectUnit_io_out_redirect_valid;	// src/main/scala/componets/core.scala:45:37
  wire [31:0] _branchRedirectUnit_io_out_redirect_target;	// src/main/scala/componets/core.scala:45:37
  wire [1:0]  _forwardUnit_io_out_forward1;	// src/main/scala/componets/core.scala:44:37
  wire [1:0]  _forwardUnit_io_out_forward2;	// src/main/scala/componets/core.scala:44:37
  wire [31:0] _forwardUnit_io_out_forward_mem;	// src/main/scala/componets/core.scala:44:37
  wire [31:0] _forwardUnit_io_out_forward_wb;	// src/main/scala/componets/core.scala:44:37
  wire        _forwardUnit_io_out_forward_lwsw;	// src/main/scala/componets/core.scala:44:37
  wire [31:0] _forwardUnit_io_out_forward_lwsw_data;	// src/main/scala/componets/core.scala:44:37
  wire        _hazardDetectUnit_io_out_is_hazard;	// src/main/scala/componets/core.scala:43:37
  wire        _pipelineControlUnit_io_out_pc_stall;	// src/main/scala/componets/core.scala:42:37
  wire        _pipelineControlUnit_io_out_pc_redirect_valid;	// src/main/scala/componets/core.scala:42:37
  wire [31:0] _pipelineControlUnit_io_out_pc_redirect_target;	// src/main/scala/componets/core.scala:42:37
  wire        _pipelineControlUnit_io_out_if_id_stall;	// src/main/scala/componets/core.scala:42:37
  wire        _pipelineControlUnit_io_out_if_id_flush;	// src/main/scala/componets/core.scala:42:37
  wire        _pipelineControlUnit_io_out_id_ex_flush;	// src/main/scala/componets/core.scala:42:37
  wire [31:0] _mem_wb_1_io_out_gpr_wd3;	// src/main/scala/componets/core.scala:40:26
  wire        _mem_wb_io_out_control_rg_we;	// src/main/scala/componets/core.scala:39:25
  wire [31:0] _mem_wb_io_out_if_data_inst;	// src/main/scala/componets/core.scala:39:25
  wire        _ex_mem_io_out_control_is_csr_inst;	// src/main/scala/componets/core.scala:38:25
  wire        _ex_mem_io_out_control_is_load_inst;	// src/main/scala/componets/core.scala:38:25
  wire        _ex_mem_io_out_control_rg_we;	// src/main/scala/componets/core.scala:38:25
  wire [2:0]  _ex_mem_io_out_control_reg_w_data;	// src/main/scala/componets/core.scala:38:25
  wire [1:0]  _ex_mem_io_out_control_mem_code;	// src/main/scala/componets/core.scala:38:25
  wire [1:0]  _ex_mem_io_out_control_mem_size;	// src/main/scala/componets/core.scala:38:25
  wire [2:0]  _ex_mem_io_out_control_sys_code;	// src/main/scala/componets/core.scala:38:25
  wire [4:0]  _ex_mem_io_out_control_rd;	// src/main/scala/componets/core.scala:38:25
  wire [11:0] _ex_mem_io_out_control_csr_wad;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_out_alu_out;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_if_data_cur_pc;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_if_data_cur_pc_4;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_if_data_inst;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_csr_data_mtvec;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_csr_data_mepc;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_csr_data_mstatus;	// src/main/scala/componets/core.scala:38:25
  wire [31:0] _ex_mem_io_out_csr_data_csr_rd;	// src/main/scala/componets/core.scala:38:25
  wire        _id_ex_io_out_control_is_csr_inst;	// src/main/scala/componets/core.scala:37:25
  wire        _id_ex_io_out_control_is_load_inst;	// src/main/scala/componets/core.scala:37:25
  wire        _id_ex_io_out_control_rg_we;	// src/main/scala/componets/core.scala:37:25
  wire [2:0]  _id_ex_io_out_control_reg_w_data;	// src/main/scala/componets/core.scala:37:25
  wire [3:0]  _id_ex_io_out_control_alu_code;	// src/main/scala/componets/core.scala:37:25
  wire [3:0]  _id_ex_io_out_control_jmp_code;	// src/main/scala/componets/core.scala:37:25
  wire [1:0]  _id_ex_io_out_control_mem_code;	// src/main/scala/componets/core.scala:37:25
  wire [1:0]  _id_ex_io_out_control_mem_size;	// src/main/scala/componets/core.scala:37:25
  wire [2:0]  _id_ex_io_out_control_sys_code;	// src/main/scala/componets/core.scala:37:25
  wire [1:0]  _id_ex_io_out_control_rs1_src;	// src/main/scala/componets/core.scala:37:25
  wire [1:0]  _id_ex_io_out_control_rs2_src;	// src/main/scala/componets/core.scala:37:25
  wire        _id_ex_io_out_control_mem_en;	// src/main/scala/componets/core.scala:37:25
  wire [4:0]  _id_ex_io_out_control_rd;	// src/main/scala/componets/core.scala:37:25
  wire [11:0] _id_ex_io_out_control_csr_wad;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_rs1;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_rs2;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_imm;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_mtvec;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_mepc;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_mstatus;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_out_csr_rd;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_if_data_cur_pc;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_if_data_cur_pc_4;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _id_ex_io_out_if_data_inst;	// src/main/scala/componets/core.scala:37:25
  wire [31:0] _if_id_io_out_cur_pc;	// src/main/scala/componets/core.scala:36:25
  wire [31:0] _if_id_io_out_cur_pc_4;	// src/main/scala/componets/core.scala:36:25
  wire [31:0] _if_id_io_out_inst;	// src/main/scala/componets/core.scala:36:25
  wire [31:0] _wb_io_ctrl_out_halt_pc;	// src/main/scala/componets/core.scala:34:20
  wire        _wb_io_ctrl_out_halt_jmp;	// src/main/scala/componets/core.scala:34:20
  wire [31:0] _wb_io_ctrl_out_mstatus_data;	// src/main/scala/componets/core.scala:34:20
  wire [31:0] _wb_io_ctrl_out_mcause_data;	// src/main/scala/componets/core.scala:34:20
  wire [31:0] _wb_io_ctrl_out_mepc_data;	// src/main/scala/componets/core.scala:34:20
  wire        _wb_io_ctrl_out_csr_we;	// src/main/scala/componets/core.scala:34:20
  wire [31:0] _wb_io_ctrl_out_gpr_wd3;	// src/main/scala/componets/core.scala:34:20
  wire        _wb_io_ctrl_out_gpr_we3;	// src/main/scala/componets/core.scala:34:20
  wire [2:0]  _wb_io_ctrl_out_sys_code;	// src/main/scala/componets/core.scala:34:20
  wire [31:0] _wb_io_ctrl_out_csr_wd;	// src/main/scala/componets/core.scala:34:20
  wire        _lsu_io_ctrl_out_control_is_csr_inst;	// src/main/scala/componets/core.scala:33:21
  wire        _lsu_io_ctrl_out_control_is_load_inst;	// src/main/scala/componets/core.scala:33:21
  wire        _lsu_io_ctrl_out_control_rg_we;	// src/main/scala/componets/core.scala:33:21
  wire [2:0]  _lsu_io_ctrl_out_control_reg_w_data;	// src/main/scala/componets/core.scala:33:21
  wire [1:0]  _lsu_io_ctrl_out_control_mem_code;	// src/main/scala/componets/core.scala:33:21
  wire [1:0]  _lsu_io_ctrl_out_control_mem_size;	// src/main/scala/componets/core.scala:33:21
  wire [2:0]  _lsu_io_ctrl_out_control_sys_code;	// src/main/scala/componets/core.scala:33:21
  wire [4:0]  _lsu_io_ctrl_out_control_rd;	// src/main/scala/componets/core.scala:33:21
  wire [11:0] _lsu_io_ctrl_out_control_csr_wad;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_out_mem_out;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_out_fu_alu;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_if_data_cur_pc;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_if_data_cur_pc_4;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_if_data_inst;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_csr_data_mtvec;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_csr_data_mepc;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_csr_data_mstatus;	// src/main/scala/componets/core.scala:33:21
  wire [31:0] _lsu_io_ctrl_out_csr_data_csr_rd;	// src/main/scala/componets/core.scala:33:21
  wire        _ex_io_ctrl_out_control_is_csr_inst;	// src/main/scala/componets/core.scala:32:20
  wire        _ex_io_ctrl_out_control_is_load_inst;	// src/main/scala/componets/core.scala:32:20
  wire        _ex_io_ctrl_out_control_rg_we;	// src/main/scala/componets/core.scala:32:20
  wire [2:0]  _ex_io_ctrl_out_control_reg_w_data;	// src/main/scala/componets/core.scala:32:20
  wire [1:0]  _ex_io_ctrl_out_control_mem_code;	// src/main/scala/componets/core.scala:32:20
  wire [1:0]  _ex_io_ctrl_out_control_mem_size;	// src/main/scala/componets/core.scala:32:20
  wire [2:0]  _ex_io_ctrl_out_control_sys_code;	// src/main/scala/componets/core.scala:32:20
  wire        _ex_io_ctrl_out_control_mem_en;	// src/main/scala/componets/core.scala:32:20
  wire [4:0]  _ex_io_ctrl_out_control_rd;	// src/main/scala/componets/core.scala:32:20
  wire [11:0] _ex_io_ctrl_out_control_csr_wad;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_out_alu_out;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_out_mem_wd;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_if_data_cur_pc;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_if_data_cur_pc_4;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_if_data_inst;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_csr_data_mtvec;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_csr_data_mepc;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_csr_data_mstatus;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_ctrl_out_csr_data_csr_rd;	// src/main/scala/componets/core.scala:32:20
  wire        _ex_io_out_notVR_jmp_valid;	// src/main/scala/componets/core.scala:32:20
  wire [31:0] _ex_io_out_notVR_jmp_pc;	// src/main/scala/componets/core.scala:32:20
  wire        _id_io_ctrl_out_control_is_csr_inst;	// src/main/scala/componets/core.scala:31:20
  wire        _id_io_ctrl_out_control_is_load_inst;	// src/main/scala/componets/core.scala:31:20
  wire        _id_io_ctrl_out_control_rg_we;	// src/main/scala/componets/core.scala:31:20
  wire [2:0]  _id_io_ctrl_out_control_reg_w_data;	// src/main/scala/componets/core.scala:31:20
  wire [3:0]  _id_io_ctrl_out_control_alu_code;	// src/main/scala/componets/core.scala:31:20
  wire [3:0]  _id_io_ctrl_out_control_jmp_code;	// src/main/scala/componets/core.scala:31:20
  wire [1:0]  _id_io_ctrl_out_control_mem_code;	// src/main/scala/componets/core.scala:31:20
  wire [1:0]  _id_io_ctrl_out_control_mem_size;	// src/main/scala/componets/core.scala:31:20
  wire [2:0]  _id_io_ctrl_out_control_sys_code;	// src/main/scala/componets/core.scala:31:20
  wire [1:0]  _id_io_ctrl_out_control_sys_src1;	// src/main/scala/componets/core.scala:31:20
  wire [1:0]  _id_io_ctrl_out_control_rs1_src;	// src/main/scala/componets/core.scala:31:20
  wire [1:0]  _id_io_ctrl_out_control_rs2_src;	// src/main/scala/componets/core.scala:31:20
  wire        _id_io_ctrl_out_control_mem_en;	// src/main/scala/componets/core.scala:31:20
  wire [2:0]  _id_io_ctrl_out_control_imm_type;	// src/main/scala/componets/core.scala:31:20
  wire [4:0]  _id_io_ctrl_out_control_rs1;	// src/main/scala/componets/core.scala:31:20
  wire [4:0]  _id_io_ctrl_out_control_rs2;	// src/main/scala/componets/core.scala:31:20
  wire [4:0]  _id_io_ctrl_out_control_rd;	// src/main/scala/componets/core.scala:31:20
  wire [11:0] _id_io_ctrl_out_control_csr_wad;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_rs1;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_rs2;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_imm;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_mtvec;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_mepc;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_mstatus;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_out_csr_rd;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_if_data_cur_pc;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_if_data_cur_pc_4;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _id_io_ctrl_out_if_data_inst;	// src/main/scala/componets/core.scala:31:20
  wire [31:0] _ifu_io_out_cur_pc;	// src/main/scala/componets/core.scala:30:21
  wire [31:0] _ifu_io_out_cur_pc_4;	// src/main/scala/componets/core.scala:30:21
  wire [31:0] _ifu_io_out_inst;	// src/main/scala/componets/core.scala:30:21
  IF ifu (	// src/main/scala/componets/core.scala:30:21
    .clock            (clock),
    .reset            (reset),
    .io_in1_jmp_valid (_pipelineControlUnit_io_out_pc_redirect_valid),	// src/main/scala/componets/core.scala:42:37
    .io_in1_jmp_pc    (_pipelineControlUnit_io_out_pc_redirect_target),	// src/main/scala/componets/core.scala:42:37
    .io_in1_stall     (_pipelineControlUnit_io_out_pc_stall),	// src/main/scala/componets/core.scala:42:37
    .io_out_cur_pc    (_ifu_io_out_cur_pc),
    .io_out_cur_pc_4  (_ifu_io_out_cur_pc_4),
    .io_out_inst      (_ifu_io_out_inst)
  );
  ID id (	// src/main/scala/componets/core.scala:31:20
    .clock                             (clock),
    .reset                             (reset),
    .io_in1_IfId_cur_pc                (_if_id_io_out_cur_pc),	// src/main/scala/componets/core.scala:36:25
    .io_in1_IfId_cur_pc_4              (_if_id_io_out_cur_pc_4),	// src/main/scala/componets/core.scala:36:25
    .io_in1_IfId_inst                  (_if_id_io_out_inst),	// src/main/scala/componets/core.scala:36:25
    .io_in1_gpr_ad3                    (_lsu_io_ctrl_out_control_rd),	// src/main/scala/componets/core.scala:33:21
    .io_in1_gpr_wd3                    (_wb_io_ctrl_out_gpr_wd3),	// src/main/scala/componets/core.scala:34:20
    .io_in1_gpr_we3                    (_wb_io_ctrl_out_gpr_we3),	// src/main/scala/componets/core.scala:34:20
    .io_in1_csr_wad                    (_lsu_io_ctrl_out_control_csr_wad),	// src/main/scala/componets/core.scala:33:21
    .io_in1_csr_wd                     (_wb_io_ctrl_out_csr_wd),	// src/main/scala/componets/core.scala:34:20
    .io_in1_csr_we                     (_wb_io_ctrl_out_csr_we),	// src/main/scala/componets/core.scala:34:20
    .io_in1_csr_halt_data_sys_code     (_wb_io_ctrl_out_sys_code),	// src/main/scala/componets/core.scala:34:20
    .io_in1_csr_halt_data_mstatus_data (_wb_io_ctrl_out_mstatus_data),	// src/main/scala/componets/core.scala:34:20
    .io_in1_csr_halt_data_mcause_data  (_wb_io_ctrl_out_mcause_data),	// src/main/scala/componets/core.scala:34:20
    .io_in1_csr_halt_data_mepc_data    (_wb_io_ctrl_out_mepc_data),	// src/main/scala/componets/core.scala:34:20
    .io_ctrl_out_control_is_csr_inst   (_id_io_ctrl_out_control_is_csr_inst),
    .io_ctrl_out_control_is_load_inst  (_id_io_ctrl_out_control_is_load_inst),
    .io_ctrl_out_control_rg_we         (_id_io_ctrl_out_control_rg_we),
    .io_ctrl_out_control_reg_w_data    (_id_io_ctrl_out_control_reg_w_data),
    .io_ctrl_out_control_alu_code      (_id_io_ctrl_out_control_alu_code),
    .io_ctrl_out_control_jmp_code      (_id_io_ctrl_out_control_jmp_code),
    .io_ctrl_out_control_mem_code      (_id_io_ctrl_out_control_mem_code),
    .io_ctrl_out_control_mem_size      (_id_io_ctrl_out_control_mem_size),
    .io_ctrl_out_control_sys_code      (_id_io_ctrl_out_control_sys_code),
    .io_ctrl_out_control_sys_src1      (_id_io_ctrl_out_control_sys_src1),
    .io_ctrl_out_control_rs1_src       (_id_io_ctrl_out_control_rs1_src),
    .io_ctrl_out_control_rs2_src       (_id_io_ctrl_out_control_rs2_src),
    .io_ctrl_out_control_mem_en        (_id_io_ctrl_out_control_mem_en),
    .io_ctrl_out_control_imm_type      (_id_io_ctrl_out_control_imm_type),
    .io_ctrl_out_control_rs1           (_id_io_ctrl_out_control_rs1),
    .io_ctrl_out_control_rs2           (_id_io_ctrl_out_control_rs2),
    .io_ctrl_out_control_rd            (_id_io_ctrl_out_control_rd),
    .io_ctrl_out_control_csr_wad       (_id_io_ctrl_out_control_csr_wad),
    .io_ctrl_out_out_rs1               (_id_io_ctrl_out_out_rs1),
    .io_ctrl_out_out_rs2               (_id_io_ctrl_out_out_rs2),
    .io_ctrl_out_out_imm               (_id_io_ctrl_out_out_imm),
    .io_ctrl_out_out_mtvec             (_id_io_ctrl_out_out_mtvec),
    .io_ctrl_out_out_mepc              (_id_io_ctrl_out_out_mepc),
    .io_ctrl_out_out_mstatus           (_id_io_ctrl_out_out_mstatus),
    .io_ctrl_out_out_csr_rd            (_id_io_ctrl_out_out_csr_rd),
    .io_ctrl_out_if_data_cur_pc        (_id_io_ctrl_out_if_data_cur_pc),
    .io_ctrl_out_if_data_cur_pc_4      (_id_io_ctrl_out_if_data_cur_pc_4),
    .io_ctrl_out_if_data_inst          (_id_io_ctrl_out_if_data_inst)
  );
  EX ex (	// src/main/scala/componets/core.scala:32:20
    .io_in1_control_is_csr_inst       (_id_ex_io_out_control_is_csr_inst),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_is_load_inst      (_id_ex_io_out_control_is_load_inst),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_rg_we             (_id_ex_io_out_control_rg_we),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_reg_w_data        (_id_ex_io_out_control_reg_w_data),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_alu_code          (_id_ex_io_out_control_alu_code),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_jmp_code          (_id_ex_io_out_control_jmp_code),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_mem_code          (_id_ex_io_out_control_mem_code),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_mem_size          (_id_ex_io_out_control_mem_size),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_sys_code          (_id_ex_io_out_control_sys_code),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_rs1_src           (_id_ex_io_out_control_rs1_src),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_rs2_src           (_id_ex_io_out_control_rs2_src),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_mem_en            (_id_ex_io_out_control_mem_en),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_rd                (_id_ex_io_out_control_rd),	// src/main/scala/componets/core.scala:37:25
    .io_in1_control_csr_wad           (_id_ex_io_out_control_csr_wad),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_rs1                   (_id_ex_io_out_out_rs1),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_rs2                   (_id_ex_io_out_out_rs2),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_imm                   (_id_ex_io_out_out_imm),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_mtvec                 (_id_ex_io_out_out_mtvec),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_mepc                  (_id_ex_io_out_out_mepc),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_mstatus               (_id_ex_io_out_out_mstatus),	// src/main/scala/componets/core.scala:37:25
    .io_in1_out_csr_rd                (_id_ex_io_out_out_csr_rd),	// src/main/scala/componets/core.scala:37:25
    .io_in1_if_data_cur_pc            (_id_ex_io_out_if_data_cur_pc),	// src/main/scala/componets/core.scala:37:25
    .io_in1_if_data_cur_pc_4          (_id_ex_io_out_if_data_cur_pc_4),	// src/main/scala/componets/core.scala:37:25
    .io_in1_if_data_inst              (_id_ex_io_out_if_data_inst),	// src/main/scala/componets/core.scala:37:25
    .io_in1_halt_jmp                  (_wb_io_ctrl_out_halt_jmp),	// src/main/scala/componets/core.scala:34:20
    .io_in1_halt_pc                   (_wb_io_ctrl_out_halt_pc),	// src/main/scala/componets/core.scala:34:20
    .io_in1_forward1                  (_forwardUnit_io_out_forward1),	// src/main/scala/componets/core.scala:44:37
    .io_in1_forward2                  (_forwardUnit_io_out_forward2),	// src/main/scala/componets/core.scala:44:37
    .io_in1_forward_mem               (_forwardUnit_io_out_forward_mem),	// src/main/scala/componets/core.scala:44:37
    .io_in1_forward_wb                (_forwardUnit_io_out_forward_wb),	// src/main/scala/componets/core.scala:44:37
    .io_ctrl_out_control_is_csr_inst  (_ex_io_ctrl_out_control_is_csr_inst),
    .io_ctrl_out_control_is_load_inst (_ex_io_ctrl_out_control_is_load_inst),
    .io_ctrl_out_control_rg_we        (_ex_io_ctrl_out_control_rg_we),
    .io_ctrl_out_control_reg_w_data   (_ex_io_ctrl_out_control_reg_w_data),
    .io_ctrl_out_control_mem_code     (_ex_io_ctrl_out_control_mem_code),
    .io_ctrl_out_control_mem_size     (_ex_io_ctrl_out_control_mem_size),
    .io_ctrl_out_control_sys_code     (_ex_io_ctrl_out_control_sys_code),
    .io_ctrl_out_control_mem_en       (_ex_io_ctrl_out_control_mem_en),
    .io_ctrl_out_control_rd           (_ex_io_ctrl_out_control_rd),
    .io_ctrl_out_control_csr_wad      (_ex_io_ctrl_out_control_csr_wad),
    .io_ctrl_out_out_alu_out          (_ex_io_ctrl_out_out_alu_out),
    .io_ctrl_out_out_mem_wd           (_ex_io_ctrl_out_out_mem_wd),
    .io_ctrl_out_if_data_cur_pc       (_ex_io_ctrl_out_if_data_cur_pc),
    .io_ctrl_out_if_data_cur_pc_4     (_ex_io_ctrl_out_if_data_cur_pc_4),
    .io_ctrl_out_if_data_inst         (_ex_io_ctrl_out_if_data_inst),
    .io_ctrl_out_csr_data_mtvec       (_ex_io_ctrl_out_csr_data_mtvec),
    .io_ctrl_out_csr_data_mepc        (_ex_io_ctrl_out_csr_data_mepc),
    .io_ctrl_out_csr_data_mstatus     (_ex_io_ctrl_out_csr_data_mstatus),
    .io_ctrl_out_csr_data_csr_rd      (_ex_io_ctrl_out_csr_data_csr_rd),
    .io_out_notVR_jmp_valid           (_ex_io_out_notVR_jmp_valid),
    .io_out_notVR_jmp_pc              (_ex_io_out_notVR_jmp_pc)
  );
  LSU lsu (	// src/main/scala/componets/core.scala:33:21
    .clock                            (clock),
    .io_in1_control_is_csr_inst       (_ex_mem_io_out_control_is_csr_inst),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_is_load_inst      (_ex_mem_io_out_control_is_load_inst),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_rg_we             (_ex_mem_io_out_control_rg_we),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_reg_w_data        (_ex_mem_io_out_control_reg_w_data),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_mem_code          (_ex_mem_io_out_control_mem_code),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_mem_size          (_ex_mem_io_out_control_mem_size),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_sys_code          (_ex_mem_io_out_control_sys_code),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_rd                (_ex_mem_io_out_control_rd),	// src/main/scala/componets/core.scala:38:25
    .io_in1_control_csr_wad           (_ex_mem_io_out_control_csr_wad),	// src/main/scala/componets/core.scala:38:25
    .io_in1_out_alu_out               (_ex_mem_io_out_out_alu_out),	// src/main/scala/componets/core.scala:38:25
    .io_in1_if_data_cur_pc            (_ex_mem_io_out_if_data_cur_pc),	// src/main/scala/componets/core.scala:38:25
    .io_in1_if_data_cur_pc_4          (_ex_mem_io_out_if_data_cur_pc_4),	// src/main/scala/componets/core.scala:38:25
    .io_in1_if_data_inst              (_ex_mem_io_out_if_data_inst),	// src/main/scala/componets/core.scala:38:25
    .io_in1_csr_data_mtvec            (_ex_mem_io_out_csr_data_mtvec),	// src/main/scala/componets/core.scala:38:25
    .io_in1_csr_data_mepc             (_ex_mem_io_out_csr_data_mepc),	// src/main/scala/componets/core.scala:38:25
    .io_in1_csr_data_mstatus          (_ex_mem_io_out_csr_data_mstatus),	// src/main/scala/componets/core.scala:38:25
    .io_in1_csr_data_csr_rd           (_ex_mem_io_out_csr_data_csr_rd),	// src/main/scala/componets/core.scala:38:25
    .io_in1_forward_lwsw              (_forwardUnit_io_out_forward_lwsw),	// src/main/scala/componets/core.scala:44:37
    .io_in1_forward_lwsw_data         (_forwardUnit_io_out_forward_lwsw_data),	// src/main/scala/componets/core.scala:44:37
    .io_in1_next_control_mem_size     (_ex_io_ctrl_out_control_mem_size),	// src/main/scala/componets/core.scala:32:20
    .io_in1_next_control_mem_en       (_ex_io_ctrl_out_control_mem_en),	// src/main/scala/componets/core.scala:32:20
    .io_in1_next_alu_out              (_ex_io_ctrl_out_out_alu_out),	// src/main/scala/componets/core.scala:32:20
    .io_in1_next_mem_wb               (_ex_io_ctrl_out_out_mem_wd),	// src/main/scala/componets/core.scala:32:20
    .io_ctrl_out_control_is_csr_inst  (_lsu_io_ctrl_out_control_is_csr_inst),
    .io_ctrl_out_control_is_load_inst (_lsu_io_ctrl_out_control_is_load_inst),
    .io_ctrl_out_control_rg_we        (_lsu_io_ctrl_out_control_rg_we),
    .io_ctrl_out_control_reg_w_data   (_lsu_io_ctrl_out_control_reg_w_data),
    .io_ctrl_out_control_mem_code     (_lsu_io_ctrl_out_control_mem_code),
    .io_ctrl_out_control_mem_size     (_lsu_io_ctrl_out_control_mem_size),
    .io_ctrl_out_control_sys_code     (_lsu_io_ctrl_out_control_sys_code),
    .io_ctrl_out_control_rd           (_lsu_io_ctrl_out_control_rd),
    .io_ctrl_out_control_csr_wad      (_lsu_io_ctrl_out_control_csr_wad),
    .io_ctrl_out_out_mem_out          (_lsu_io_ctrl_out_out_mem_out),
    .io_ctrl_out_out_fu_alu           (_lsu_io_ctrl_out_out_fu_alu),
    .io_ctrl_out_if_data_cur_pc       (_lsu_io_ctrl_out_if_data_cur_pc),
    .io_ctrl_out_if_data_cur_pc_4     (_lsu_io_ctrl_out_if_data_cur_pc_4),
    .io_ctrl_out_if_data_inst         (_lsu_io_ctrl_out_if_data_inst),
    .io_ctrl_out_csr_data_mtvec       (_lsu_io_ctrl_out_csr_data_mtvec),
    .io_ctrl_out_csr_data_mepc        (_lsu_io_ctrl_out_csr_data_mepc),
    .io_ctrl_out_csr_data_mstatus     (_lsu_io_ctrl_out_csr_data_mstatus),
    .io_ctrl_out_csr_data_csr_rd      (_lsu_io_ctrl_out_csr_data_csr_rd),
    .Addr_cpu                         	(Addr_cpu                          ),
    .WD_cpu                           	(WD_cpu                            ),
    .WE_cpu                           	(WE_cpu                            ),
    .LEN_cpu                          	(LEN_cpu                           ),
    .dout_cpu                         	(dout_cpu                          )
  );

  WB wb (	// src/main/scala/componets/core.scala:34:20
    .io_in1_control_rg_we      (_lsu_io_ctrl_out_control_rg_we),	// src/main/scala/componets/core.scala:33:21
    .io_in1_control_reg_w_data (_lsu_io_ctrl_out_control_reg_w_data),	// src/main/scala/componets/core.scala:33:21
    .io_in1_control_sys_code   (_lsu_io_ctrl_out_control_sys_code),	// src/main/scala/componets/core.scala:33:21
    .io_in1_out_mem_out        (_lsu_io_ctrl_out_out_mem_out),	// src/main/scala/componets/core.scala:33:21
    .io_in1_out_fu_alu         (_lsu_io_ctrl_out_out_fu_alu),	// src/main/scala/componets/core.scala:33:21
    .io_in1_if_data_cur_pc     (_lsu_io_ctrl_out_if_data_cur_pc),	// src/main/scala/componets/core.scala:33:21
    .io_in1_if_data_cur_pc_4   (_lsu_io_ctrl_out_if_data_cur_pc_4),	// src/main/scala/componets/core.scala:33:21
    .io_in1_csr_data_mtvec     (_lsu_io_ctrl_out_csr_data_mtvec),	// src/main/scala/componets/core.scala:33:21
    .io_in1_csr_data_mepc      (_lsu_io_ctrl_out_csr_data_mepc),	// src/main/scala/componets/core.scala:33:21
    .io_in1_csr_data_mstatus   (_lsu_io_ctrl_out_csr_data_mstatus),	// src/main/scala/componets/core.scala:33:21
    .io_in1_csr_data_csr_rd    (_lsu_io_ctrl_out_csr_data_csr_rd),	// src/main/scala/componets/core.scala:33:21
    .io_ctrl_out_halt_pc       (_wb_io_ctrl_out_halt_pc),
    .io_ctrl_out_halt_jmp      (_wb_io_ctrl_out_halt_jmp),
    .io_ctrl_out_mstatus_data  (_wb_io_ctrl_out_mstatus_data),
    .io_ctrl_out_mcause_data   (_wb_io_ctrl_out_mcause_data),
    .io_ctrl_out_mepc_data     (_wb_io_ctrl_out_mepc_data),
    .io_ctrl_out_csr_we        (_wb_io_ctrl_out_csr_we),
    .io_ctrl_out_gpr_wd3       (_wb_io_ctrl_out_gpr_wd3),
    .io_ctrl_out_gpr_we3       (_wb_io_ctrl_out_gpr_we3),
    .io_ctrl_out_sys_code      (_wb_io_ctrl_out_sys_code),
    .io_ctrl_out_csr_wd        (_wb_io_ctrl_out_csr_wd)
  );
  PipelineReg if_id (	// src/main/scala/componets/core.scala:36:25
    .clock           (clock),
    .reset           (reset),
    .io_in_cur_pc    (_ifu_io_out_cur_pc),	// src/main/scala/componets/core.scala:30:21
    .io_in_cur_pc_4  (_ifu_io_out_cur_pc_4),	// src/main/scala/componets/core.scala:30:21
    .io_in_inst      (_ifu_io_out_inst),	// src/main/scala/componets/core.scala:30:21
    .io_ctrl_stall   (_pipelineControlUnit_io_out_if_id_stall),	// src/main/scala/componets/core.scala:42:37
    .io_ctrl_flush   (_pipelineControlUnit_io_out_if_id_flush),	// src/main/scala/componets/core.scala:42:37
    .io_out_cur_pc   (_if_id_io_out_cur_pc),
    .io_out_cur_pc_4 (_if_id_io_out_cur_pc_4),
    .io_out_inst     (_if_id_io_out_inst)
  );
  PipelineReg_1 id_ex (	// src/main/scala/componets/core.scala:37:25
    .clock                       (clock),
    .reset                       (reset),
    .io_in_control_is_csr_inst   (_id_io_ctrl_out_control_is_csr_inst),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_is_load_inst  (_id_io_ctrl_out_control_is_load_inst),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_rg_we         (_id_io_ctrl_out_control_rg_we),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_reg_w_data    (_id_io_ctrl_out_control_reg_w_data),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_alu_code      (_id_io_ctrl_out_control_alu_code),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_jmp_code      (_id_io_ctrl_out_control_jmp_code),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_mem_code      (_id_io_ctrl_out_control_mem_code),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_mem_size      (_id_io_ctrl_out_control_mem_size),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_sys_code      (_id_io_ctrl_out_control_sys_code),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_sys_src1      (_id_io_ctrl_out_control_sys_src1),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_rs1_src       (_id_io_ctrl_out_control_rs1_src),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_rs2_src       (_id_io_ctrl_out_control_rs2_src),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_mem_en        (_id_io_ctrl_out_control_mem_en),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_imm_type      (_id_io_ctrl_out_control_imm_type),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_rs1           (_id_io_ctrl_out_control_rs1),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_rs2           (_id_io_ctrl_out_control_rs2),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_rd            (_id_io_ctrl_out_control_rd),	// src/main/scala/componets/core.scala:31:20
    .io_in_control_csr_wad       (_id_io_ctrl_out_control_csr_wad),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_rs1               (_id_io_ctrl_out_out_rs1),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_rs2               (_id_io_ctrl_out_out_rs2),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_imm               (_id_io_ctrl_out_out_imm),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_mtvec             (_id_io_ctrl_out_out_mtvec),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_mepc              (_id_io_ctrl_out_out_mepc),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_mstatus           (_id_io_ctrl_out_out_mstatus),	// src/main/scala/componets/core.scala:31:20
    .io_in_out_csr_rd            (_id_io_ctrl_out_out_csr_rd),	// src/main/scala/componets/core.scala:31:20
    .io_in_if_data_cur_pc        (_id_io_ctrl_out_if_data_cur_pc),	// src/main/scala/componets/core.scala:31:20
    .io_in_if_data_cur_pc_4      (_id_io_ctrl_out_if_data_cur_pc_4),	// src/main/scala/componets/core.scala:31:20
    .io_in_if_data_inst          (_id_io_ctrl_out_if_data_inst),	// src/main/scala/componets/core.scala:31:20
    .io_ctrl_flush               (_pipelineControlUnit_io_out_id_ex_flush),	// src/main/scala/componets/core.scala:42:37
    .io_out_control_is_csr_inst  (_id_ex_io_out_control_is_csr_inst),
    .io_out_control_is_load_inst (_id_ex_io_out_control_is_load_inst),
    .io_out_control_rg_we        (_id_ex_io_out_control_rg_we),
    .io_out_control_reg_w_data   (_id_ex_io_out_control_reg_w_data),
    .io_out_control_alu_code     (_id_ex_io_out_control_alu_code),
    .io_out_control_jmp_code     (_id_ex_io_out_control_jmp_code),
    .io_out_control_mem_code     (_id_ex_io_out_control_mem_code),
    .io_out_control_mem_size     (_id_ex_io_out_control_mem_size),
    .io_out_control_sys_code     (_id_ex_io_out_control_sys_code),
    .io_out_control_sys_src1     (io_debugPort_control_sys_src1),
    .io_out_control_rs1_src      (_id_ex_io_out_control_rs1_src),
    .io_out_control_rs2_src      (_id_ex_io_out_control_rs2_src),
    .io_out_control_mem_en       (_id_ex_io_out_control_mem_en),
    .io_out_control_imm_type     (io_debugPort_control_imm_type),
    .io_out_control_rs1          (io_debugPort_control_rs1),
    .io_out_control_rs2          (io_debugPort_control_rs2),
    .io_out_control_rd           (_id_ex_io_out_control_rd),
    .io_out_control_csr_wad      (_id_ex_io_out_control_csr_wad),
    .io_out_out_rs1              (_id_ex_io_out_out_rs1),
    .io_out_out_rs2              (_id_ex_io_out_out_rs2),
    .io_out_out_imm              (_id_ex_io_out_out_imm),
    .io_out_out_mtvec            (_id_ex_io_out_out_mtvec),
    .io_out_out_mepc             (_id_ex_io_out_out_mepc),
    .io_out_out_mstatus          (_id_ex_io_out_out_mstatus),
    .io_out_out_csr_rd           (_id_ex_io_out_out_csr_rd),
    .io_out_if_data_cur_pc       (_id_ex_io_out_if_data_cur_pc),
    .io_out_if_data_cur_pc_4     (_id_ex_io_out_if_data_cur_pc_4),
    .io_out_if_data_inst         (_id_ex_io_out_if_data_inst)
  );
  PipelineReg_2 ex_mem (	// src/main/scala/componets/core.scala:38:25
    .clock                       (clock),
    .reset                       (reset),
    .io_in_control_is_csr_inst   (_ex_io_ctrl_out_control_is_csr_inst),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_is_load_inst  (_ex_io_ctrl_out_control_is_load_inst),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_rg_we         (_ex_io_ctrl_out_control_rg_we),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_reg_w_data    (_ex_io_ctrl_out_control_reg_w_data),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_mem_code      (_ex_io_ctrl_out_control_mem_code),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_mem_size      (_ex_io_ctrl_out_control_mem_size),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_sys_code      (_ex_io_ctrl_out_control_sys_code),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_rd            (_ex_io_ctrl_out_control_rd),	// src/main/scala/componets/core.scala:32:20
    .io_in_control_csr_wad       (_ex_io_ctrl_out_control_csr_wad),	// src/main/scala/componets/core.scala:32:20
    .io_in_out_alu_out           (_ex_io_ctrl_out_out_alu_out),	// src/main/scala/componets/core.scala:32:20
    .io_in_if_data_cur_pc        (_ex_io_ctrl_out_if_data_cur_pc),	// src/main/scala/componets/core.scala:32:20
    .io_in_if_data_cur_pc_4      (_ex_io_ctrl_out_if_data_cur_pc_4),	// src/main/scala/componets/core.scala:32:20
    .io_in_if_data_inst          (_ex_io_ctrl_out_if_data_inst),	// src/main/scala/componets/core.scala:32:20
    .io_in_csr_data_mtvec        (_ex_io_ctrl_out_csr_data_mtvec),	// src/main/scala/componets/core.scala:32:20
    .io_in_csr_data_mepc         (_ex_io_ctrl_out_csr_data_mepc),	// src/main/scala/componets/core.scala:32:20
    .io_in_csr_data_mstatus      (_ex_io_ctrl_out_csr_data_mstatus),	// src/main/scala/componets/core.scala:32:20
    .io_in_csr_data_csr_rd       (_ex_io_ctrl_out_csr_data_csr_rd),	// src/main/scala/componets/core.scala:32:20
    .io_out_control_is_csr_inst  (_ex_mem_io_out_control_is_csr_inst),
    .io_out_control_is_load_inst (_ex_mem_io_out_control_is_load_inst),
    .io_out_control_rg_we        (_ex_mem_io_out_control_rg_we),
    .io_out_control_reg_w_data   (_ex_mem_io_out_control_reg_w_data),
    .io_out_control_mem_code     (_ex_mem_io_out_control_mem_code),
    .io_out_control_mem_size     (_ex_mem_io_out_control_mem_size),
    .io_out_control_sys_code     (_ex_mem_io_out_control_sys_code),
    .io_out_control_rd           (_ex_mem_io_out_control_rd),
    .io_out_control_csr_wad      (_ex_mem_io_out_control_csr_wad),
    .io_out_out_alu_out          (_ex_mem_io_out_out_alu_out),
    .io_out_if_data_cur_pc       (_ex_mem_io_out_if_data_cur_pc),
    .io_out_if_data_cur_pc_4     (_ex_mem_io_out_if_data_cur_pc_4),
    .io_out_if_data_inst         (_ex_mem_io_out_if_data_inst),
    .io_out_csr_data_mtvec       (_ex_mem_io_out_csr_data_mtvec),
    .io_out_csr_data_mepc        (_ex_mem_io_out_csr_data_mepc),
    .io_out_csr_data_mstatus     (_ex_mem_io_out_csr_data_mstatus),
    .io_out_csr_data_csr_rd      (_ex_mem_io_out_csr_data_csr_rd)
  );
  PipelineReg_2 mem_wb (	// src/main/scala/componets/core.scala:39:25
    .clock                       (clock),
    .reset                       (reset),
    .io_in_control_is_csr_inst   (_lsu_io_ctrl_out_control_is_csr_inst),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_is_load_inst  (_lsu_io_ctrl_out_control_is_load_inst),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_rg_we         (_lsu_io_ctrl_out_control_rg_we),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_reg_w_data    (_lsu_io_ctrl_out_control_reg_w_data),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_mem_code      (_lsu_io_ctrl_out_control_mem_code),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_mem_size      (_lsu_io_ctrl_out_control_mem_size),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_sys_code      (_lsu_io_ctrl_out_control_sys_code),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_rd            (_lsu_io_ctrl_out_control_rd),	// src/main/scala/componets/core.scala:33:21
    .io_in_control_csr_wad       (_lsu_io_ctrl_out_control_csr_wad),	// src/main/scala/componets/core.scala:33:21
    .io_in_out_alu_out           (_lsu_io_ctrl_out_out_mem_out),	// src/main/scala/componets/core.scala:33:21
    .io_in_if_data_cur_pc        (_lsu_io_ctrl_out_if_data_cur_pc),	// src/main/scala/componets/core.scala:33:21
    .io_in_if_data_cur_pc_4      (_lsu_io_ctrl_out_if_data_cur_pc_4),	// src/main/scala/componets/core.scala:33:21
    .io_in_if_data_inst          (_lsu_io_ctrl_out_if_data_inst),	// src/main/scala/componets/core.scala:33:21
    .io_in_csr_data_mtvec        (_lsu_io_ctrl_out_csr_data_mtvec),	// src/main/scala/componets/core.scala:33:21
    .io_in_csr_data_mepc         (_lsu_io_ctrl_out_csr_data_mepc),	// src/main/scala/componets/core.scala:33:21
    .io_in_csr_data_mstatus      (_lsu_io_ctrl_out_csr_data_mstatus),	// src/main/scala/componets/core.scala:33:21
    .io_in_csr_data_csr_rd       (_lsu_io_ctrl_out_csr_data_csr_rd),	// src/main/scala/componets/core.scala:33:21
    /* verilator lint_off PINCONNECTEMPTY */
    .io_out_control_is_csr_inst  (/* unused */),
    .io_out_control_is_load_inst (/* unused */),
    .io_out_control_rg_we        (_mem_wb_io_out_control_rg_we),
    .io_out_control_reg_w_data   (/* unused */),
    .io_out_control_mem_code     (/* unused */),
    .io_out_control_mem_size     (/* unused */),
    .io_out_control_sys_code     (/* unused */),
    .io_out_control_rd           (/* unused */),
    .io_out_control_csr_wad      (/* unused */),
    .io_out_out_alu_out          (io_debugPort_memOutput),
    .io_out_if_data_cur_pc       (io_debugPort_pcOutput),
    .io_out_if_data_cur_pc_4     (/* unused */),
    .io_out_if_data_inst         (_mem_wb_io_out_if_data_inst),
    .io_out_csr_data_mtvec       (/* unused */),
    .io_out_csr_data_mepc        (/* unused */),
    .io_out_csr_data_mstatus     (/* unused */),
    .io_out_csr_data_csr_rd      (/* unused */)
  );
  /* verilator lint_on PINCONNECTEMPTY */
  PipelineReg_4 mem_wb_1 (	// src/main/scala/componets/core.scala:40:26
    .clock          (clock),
    .reset          (reset),
    .io_in_gpr_wd3  (_wb_io_ctrl_out_gpr_wd3),	// src/main/scala/componets/core.scala:34:20
    .io_out_gpr_wd3 (_mem_wb_1_io_out_gpr_wd3)
  );
  PipelineControlUnit pipelineControlUnit (	// src/main/scala/componets/core.scala:42:37
    .io_in_hazard_is_hazard         (_hazardDetectUnit_io_out_is_hazard),	// src/main/scala/componets/core.scala:43:37
    .io_in_redirect_redirect_valid  (_branchRedirectUnit_io_out_redirect_valid),	// src/main/scala/componets/core.scala:45:37
    .io_in_redirect_redirect_target (_branchRedirectUnit_io_out_redirect_target),	// src/main/scala/componets/core.scala:45:37
    .io_out_pc_stall                (_pipelineControlUnit_io_out_pc_stall),
    .io_out_pc_redirect_valid       (_pipelineControlUnit_io_out_pc_redirect_valid),
    .io_out_pc_redirect_target      (_pipelineControlUnit_io_out_pc_redirect_target),
    .io_out_if_id_stall             (_pipelineControlUnit_io_out_if_id_stall),
    .io_out_if_id_flush             (_pipelineControlUnit_io_out_if_id_flush),
    .io_out_id_ex_flush             (_pipelineControlUnit_io_out_id_ex_flush)
  );
  HazardDetectUnit hazardDetectUnit (	// src/main/scala/componets/core.scala:43:37
    .io_in_decoder_out_rs1_src       (_id_io_ctrl_out_control_rs1_src),	// src/main/scala/componets/core.scala:31:20
    .io_in_decoder_out_rs2_src       (_id_io_ctrl_out_control_rs2_src),	// src/main/scala/componets/core.scala:31:20
    .io_in_decoder_out_rs1           (_id_io_ctrl_out_control_rs1),	// src/main/scala/componets/core.scala:31:20
    .io_in_decoder_out_rs2           (_id_io_ctrl_out_control_rs2),	// src/main/scala/componets/core.scala:31:20
    .io_in_IfId_inst                 (_if_id_io_out_inst),	// src/main/scala/componets/core.scala:36:25
    .io_in_IdEx_control_is_load_inst (_id_ex_io_out_control_is_load_inst),	// src/main/scala/componets/core.scala:37:25
    .io_in_IdEx_control_rd           (_id_ex_io_out_control_rd),	// src/main/scala/componets/core.scala:37:25
    .io_out_is_hazard                (_hazardDetectUnit_io_out_is_hazard)
  );
  ForwardUnit forwardUnit (	// src/main/scala/componets/core.scala:44:37
    .io_in_IdEx_control_mem_en        (_id_ex_io_out_control_mem_en),	// src/main/scala/componets/core.scala:37:25
    .io_in_IdEx_if_data_inst          (_id_ex_io_out_if_data_inst),	// src/main/scala/componets/core.scala:37:25
    .io_in_ExMem_control_is_csr_inst  (_ex_mem_io_out_control_is_csr_inst),	// src/main/scala/componets/core.scala:38:25
    .io_in_ExMem_control_is_load_inst (_ex_mem_io_out_control_is_load_inst),	// src/main/scala/componets/core.scala:38:25
    .io_in_ExMem_control_rg_we        (_ex_mem_io_out_control_rg_we),	// src/main/scala/componets/core.scala:38:25
    .io_in_ExMem_out_alu_out          (_ex_mem_io_out_out_alu_out),	// src/main/scala/componets/core.scala:38:25
    .io_in_ExMem_if_data_inst         (_ex_mem_io_out_if_data_inst),	// src/main/scala/componets/core.scala:38:25
    .io_in_ExMem_csr_data_csr_rd      (_ex_mem_io_out_csr_data_csr_rd),	// src/main/scala/componets/core.scala:38:25
    .io_in_MemWb_control_rg_we        (_mem_wb_io_out_control_rg_we),	// src/main/scala/componets/core.scala:39:25
    .io_in_MemWb_if_data_inst         (_mem_wb_io_out_if_data_inst),	// src/main/scala/componets/core.scala:39:25
    .io_in_gpr_wd3                    (_mem_wb_1_io_out_gpr_wd3),	// src/main/scala/componets/core.scala:40:26
    .io_in_lwsw_data                  (_lsu_io_ctrl_out_out_mem_out),	// src/main/scala/componets/core.scala:33:21
    .io_out_forward1                  (_forwardUnit_io_out_forward1),
    .io_out_forward2                  (_forwardUnit_io_out_forward2),
    .io_out_forward_mem               (_forwardUnit_io_out_forward_mem),
    .io_out_forward_wb                (_forwardUnit_io_out_forward_wb),
    .io_out_forward_lwsw              (_forwardUnit_io_out_forward_lwsw),
    .io_out_forward_lwsw_data         (_forwardUnit_io_out_forward_lwsw_data)
  );
  BranchRedirectUnit branchRedirectUnit (	// src/main/scala/componets/core.scala:45:37
    .io_in_bru_out_jmp_valid (_ex_io_out_notVR_jmp_valid),	// src/main/scala/componets/core.scala:32:20
    .io_in_bru_out_jmp_pc    (_ex_io_out_notVR_jmp_pc),	// src/main/scala/componets/core.scala:32:20
    .io_out_redirect_valid   (_branchRedirectUnit_io_out_redirect_valid),
    .io_out_redirect_target  (_branchRedirectUnit_io_out_redirect_target)
  );
  assign io_debugPort_aluOutput = _ex_mem_io_out_out_alu_out;	// src/main/scala/componets/core.scala:24:7, :38:25
  assign io_debugPort_instOutput = _mem_wb_io_out_if_data_inst;	// src/main/scala/componets/core.scala:24:7, :39:25
  assign io_debugPort_a0reg = _id_ex_io_out_out_rs1;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_pcControl = {2'h0, _id_ex_io_out_control_jmp_code};	// src/main/scala/componets/core.scala:24:7, :37:25, :154:28
  assign io_debugPort_mem_code = _id_ex_io_out_control_mem_code;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_mem_size = _id_ex_io_out_control_mem_size;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_rg_wen = _id_ex_io_out_control_rg_we;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_is_csr_inst = _id_ex_io_out_control_is_csr_inst;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_is_load_inst = _id_ex_io_out_control_is_load_inst;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_rg_we = _id_ex_io_out_control_rg_we;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_reg_w_data = _id_ex_io_out_control_reg_w_data;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_alu_code = _id_ex_io_out_control_alu_code;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_jmp_code = _id_ex_io_out_control_jmp_code;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_mem_code = _id_ex_io_out_control_mem_code;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_mem_size = _id_ex_io_out_control_mem_size;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_sys_code = _id_ex_io_out_control_sys_code;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_rs1_src = _id_ex_io_out_control_rs1_src;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_rs2_src = _id_ex_io_out_control_rs2_src;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_mem_en = _id_ex_io_out_control_mem_en;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_rd = _id_ex_io_out_control_rd;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_control_csr_wad = _id_ex_io_out_control_csr_wad;	// src/main/scala/componets/core.scala:24:7, :37:25
  assign io_debugPort_jmp_valid = _ex_io_out_notVR_jmp_valid;	// src/main/scala/componets/core.scala:24:7, :32:20
  assign io_debugPort_is_hazard = _hazardDetectUnit_io_out_is_hazard;	// src/main/scala/componets/core.scala:24:7, :43:37
endmodule

