// Generated by CIRCT firtool-1.62.0
module CSRegs(	// src/main/scala/componets/ID/csr.scala:27:7
  input         clock,	// src/main/scala/componets/ID/csr.scala:27:7
                reset,	// src/main/scala/componets/ID/csr.scala:27:7
  input  [11:0] io_WAD,	// src/main/scala/componets/ID/csr.scala:28:16
  input         io_WE,	// src/main/scala/componets/ID/csr.scala:28:16
  input  [11:0] io_AD,	// src/main/scala/componets/ID/csr.scala:28:16
  input  [31:0] io_WD,	// src/main/scala/componets/ID/csr.scala:28:16
  output [31:0] io_RD,	// src/main/scala/componets/ID/csr.scala:28:16
                io_mtvec,	// src/main/scala/componets/ID/csr.scala:28:16
                io_mepc,	// src/main/scala/componets/ID/csr.scala:28:16
                io_mstatus,	// src/main/scala/componets/ID/csr.scala:28:16
  input  [2:0]  io_halt_data_sys_code,	// src/main/scala/componets/ID/csr.scala:28:16
  input  [31:0] io_halt_data_mstatus_data,	// src/main/scala/componets/ID/csr.scala:28:16
                io_halt_data_mcause_data,	// src/main/scala/componets/ID/csr.scala:28:16
                io_halt_data_mepc_data	// src/main/scala/componets/ID/csr.scala:28:16
);

  reg [31:0] mstatus_reg;	// src/main/scala/componets/ID/csr.scala:43:30
  reg [31:0] mtvec_reg;	// src/main/scala/componets/ID/csr.scala:44:28
  reg [31:0] mepc_reg;	// src/main/scala/componets/ID/csr.scala:45:27
  reg [31:0] mcause_reg;	// src/main/scala/componets/ID/csr.scala:46:29
  always @(posedge clock) begin	// src/main/scala/componets/ID/csr.scala:27:7
    if (reset) begin	// src/main/scala/componets/ID/csr.scala:27:7
      mstatus_reg <= 32'h0;	// src/main/scala/componets/ID/csr.scala:43:30
      mtvec_reg <= 32'h0;	// src/main/scala/componets/ID/csr.scala:43:30, :44:28
      mepc_reg <= 32'h0;	// src/main/scala/componets/ID/csr.scala:43:30, :45:27
      mcause_reg <= 32'h0;	// src/main/scala/componets/ID/csr.scala:43:30, :46:29
    end
    else begin	// src/main/scala/componets/ID/csr.scala:27:7
      automatic logic _GEN;	// src/main/scala/componets/ID/csr.scala:57:24
      automatic logic _GEN_0;	// src/main/scala/componets/ID/csr.scala:57:24
      automatic logic _GEN_1;	// src/main/scala/componets/ID/csr.scala:57:24
      automatic logic _GEN_2 = io_halt_data_sys_code == 3'h4;	// src/main/scala/componets/ID/csr.scala:66:30
      _GEN = io_WAD == 12'h305;	// src/main/scala/componets/ID/csr.scala:49:42, :57:24
      _GEN_0 = io_WAD == 12'h341;	// src/main/scala/componets/ID/csr.scala:49:42, :57:24
      _GEN_1 = io_WAD == 12'h342;	// src/main/scala/componets/ID/csr.scala:49:42, :57:24
      if (io_halt_data_sys_code == 3'h5 | _GEN_2)	// src/main/scala/componets/ID/csr.scala:56:18, :66:{30,51}, :69:21, :72:{30,50}, :73:21
        mstatus_reg <= io_halt_data_mstatus_data;	// src/main/scala/componets/ID/csr.scala:43:30
      else if (~io_WE | _GEN | _GEN_0 | _GEN_1 | io_WAD != 12'h300) begin	// src/main/scala/componets/ID/csr.scala:43:30, :45:27, :49:42, :56:18, :57:24
      end
      else	// src/main/scala/componets/ID/csr.scala:43:30, :56:18, :57:24
        mstatus_reg <= io_WD;	// src/main/scala/componets/ID/csr.scala:43:30
      if (io_WE & _GEN)	// src/main/scala/componets/ID/csr.scala:44:28, :56:18, :57:24, :58:40
        mtvec_reg <= io_WD;	// src/main/scala/componets/ID/csr.scala:44:28
      if (_GEN_2) begin	// src/main/scala/componets/ID/csr.scala:66:30
        mepc_reg <= io_halt_data_mepc_data;	// src/main/scala/componets/ID/csr.scala:45:27
        mcause_reg <= io_halt_data_mcause_data;	// src/main/scala/componets/ID/csr.scala:46:29
      end
      else begin	// src/main/scala/componets/ID/csr.scala:66:30
        if (~io_WE | _GEN | ~_GEN_0) begin	// src/main/scala/componets/ID/csr.scala:45:27, :56:18, :57:24
        end
        else	// src/main/scala/componets/ID/csr.scala:45:27, :56:18, :57:24
          mepc_reg <= io_WD;	// src/main/scala/componets/ID/csr.scala:45:27
        if (~io_WE | _GEN | _GEN_0 | ~_GEN_1) begin	// src/main/scala/componets/ID/csr.scala:45:27, :46:29, :56:18, :57:24
        end
        else	// src/main/scala/componets/ID/csr.scala:46:29, :56:18, :57:24
          mcause_reg <= io_WD;	// src/main/scala/componets/ID/csr.scala:46:29
      end
    end
  end // always @(posedge)
  assign io_RD =
    io_AD == 12'h305
      ? mtvec_reg
      : io_AD == 12'h300
          ? mstatus_reg
          : io_AD == 12'h341 ? mepc_reg : io_AD == 12'h342 ? mcause_reg : 32'h0;	// src/main/scala/componets/ID/csr.scala:27:7, :43:30, :44:28, :45:27, :46:29, :49:42
  assign io_mtvec = {mtvec_reg[31:2], 2'h0};	// src/main/scala/componets/ID/csr.scala:27:7, :44:28, :76:{20,30,42}
  assign io_mepc = mepc_reg;	// src/main/scala/componets/ID/csr.scala:27:7, :45:27
  assign io_mstatus = mstatus_reg;	// src/main/scala/componets/ID/csr.scala:27:7, :43:30
endmodule

