// Generated by CIRCT firtool-1.62.0
module Decoder(	// src/main/scala/componets/ID/Decoder.scala:45:7
  input  [31:0] io_inst,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output        io_control_is_csr_inst,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_is_load_inst,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_rg_we,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [2:0]  io_control_reg_w_data,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [3:0]  io_control_alu_code,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_jmp_code,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [1:0]  io_control_mem_code,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_mem_size,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [2:0]  io_control_sys_code,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [1:0]  io_control_sys_src1,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_rs1_src,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_rs2_src,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output        io_control_mem_en,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [2:0]  io_control_imm_type,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [4:0]  io_control_rs1,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_rs2,	// src/main/scala/componets/ID/Decoder.scala:48:16
                io_control_rd,	// src/main/scala/componets/ID/Decoder.scala:48:16
  output [11:0] io_control_csr_wad	// src/main/scala/componets/ID/Decoder.scala:48:16
);

  wire [29:0] decode_result_invInputs = ~(io_inst[31:2]);	// src/main/scala/chisel3/util/pla.scala:78:21, src/main/scala/componets/ID/Decoder.scala:48:16
  wire [1:0]  _decode_result_andMatrixOutputs_T =
    {decode_result_invInputs[2], decode_result_invInputs[3]};	// src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:53
  wire [1:0]  _decode_result_andMatrixOutputs_T_1 =
    {decode_result_invInputs[0], decode_result_invInputs[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:53
  wire [7:0]  _decode_result_andMatrixOutputs_T_2 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     decode_result_invInputs[2],
     decode_result_invInputs[3],
     decode_result_invInputs[4],
     decode_result_invInputs[11]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [8:0]  _decode_result_andMatrixOutputs_T_3 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     decode_result_invInputs[2],
     decode_result_invInputs[3],
     decode_result_invInputs[4],
     decode_result_invInputs[10],
     decode_result_invInputs[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [1:0]  _decode_result_andMatrixOutputs_T_4 =
    {io_inst[2], decode_result_invInputs[2]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [1:0]  _decode_result_andMatrixOutputs_T_6 =
    {io_inst[4], decode_result_invInputs[3]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [2:0]  _decode_result_andMatrixOutputs_T_7 =
    {decode_result_invInputs[0], io_inst[4], decode_result_invInputs[10]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [1:0]  _decode_result_andMatrixOutputs_T_12 = {io_inst[2], io_inst[4]};	// src/main/scala/chisel3/util/pla.scala:90:45, :98:53
  wire [2:0]  _decode_result_andMatrixOutputs_T_14 =
    {decode_result_invInputs[2], io_inst[5], decode_result_invInputs[4]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [3:0]  _decode_result_andMatrixOutputs_T_17 =
    {decode_result_invInputs[0], io_inst[4], io_inst[5], decode_result_invInputs[4]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [2:0]  _decode_result_andMatrixOutputs_T_18 =
    {decode_result_invInputs[0], decode_result_invInputs[2], io_inst[6]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [9:0]  _decode_result_andMatrixOutputs_T_20 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     decode_result_invInputs[2],
     io_inst[5],
     io_inst[6],
     decode_result_invInputs[10],
     decode_result_invInputs[11],
     decode_result_invInputs[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [9:0]  _decode_result_andMatrixOutputs_T_21 =
    {io_inst[0],
     io_inst[1],
     io_inst[2],
     decode_result_invInputs[1],
     decode_result_invInputs[2],
     io_inst[5],
     io_inst[6],
     decode_result_invInputs[10],
     decode_result_invInputs[11],
     decode_result_invInputs[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [6:0]  _decode_result_andMatrixOutputs_T_22 =
    {io_inst[0],
     io_inst[1],
     io_inst[2],
     io_inst[3],
     decode_result_invInputs[2],
     io_inst[5],
     io_inst[6]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [31:0] _decode_result_andMatrixOutputs_T_23 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     io_inst[4],
     io_inst[5],
     io_inst[6],
     decode_result_invInputs[5],
     decode_result_invInputs[6],
     decode_result_invInputs[7],
     decode_result_invInputs[8],
     decode_result_invInputs[9],
     decode_result_invInputs[10],
     decode_result_invInputs[11],
     decode_result_invInputs[12],
     decode_result_invInputs[13],
     decode_result_invInputs[14],
     decode_result_invInputs[15],
     decode_result_invInputs[16],
     decode_result_invInputs[17],
     decode_result_invInputs[18],
     decode_result_invInputs[19],
     decode_result_invInputs[20],
     decode_result_invInputs[21],
     decode_result_invInputs[22],
     decode_result_invInputs[23],
     decode_result_invInputs[24],
     decode_result_invInputs[25],
     decode_result_invInputs[26],
     decode_result_invInputs[27],
     decode_result_invInputs[28],
     decode_result_invInputs[29]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [5:0]  _decode_result_andMatrixOutputs_T_24 =
    {decode_result_invInputs[0],
     io_inst[4],
     decode_result_invInputs[4],
     io_inst[12],
     decode_result_invInputs[11],
     decode_result_invInputs[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [2:0]  _decode_result_andMatrixOutputs_T_25 =
    {io_inst[4], io_inst[6], io_inst[12]};	// src/main/scala/chisel3/util/pla.scala:90:45, :98:53
  wire [7:0]  _decode_result_andMatrixOutputs_T_27 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     io_inst[4],
     io_inst[5],
     io_inst[6],
     io_inst[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [3:0]  _decode_result_andMatrixOutputs_T_28 =
    {decode_result_invInputs[0], io_inst[4], decode_result_invInputs[10], io_inst[13]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [4:0]  _decode_result_andMatrixOutputs_T_29 =
    {decode_result_invInputs[0],
     io_inst[4],
     decode_result_invInputs[4],
     io_inst[13],
     decode_result_invInputs[12]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [3:0]  _decode_result_andMatrixOutputs_T_32 =
    {io_inst[4], io_inst[6], decode_result_invInputs[10], io_inst[13]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [7:0]  _decode_result_andMatrixOutputs_T_33 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     io_inst[4],
     io_inst[5],
     io_inst[6],
     io_inst[13]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [3:0]  _decode_result_andMatrixOutputs_T_35 =
    {io_inst[4], io_inst[6], io_inst[12], io_inst[13]};	// src/main/scala/chisel3/util/pla.scala:90:45, :98:53
  wire [2:0]  _decode_result_andMatrixOutputs_T_40 =
    {io_inst[4], io_inst[6], io_inst[14]};	// src/main/scala/chisel3/util/pla.scala:90:45, :98:53
  wire [8:0]  _decode_result_andMatrixOutputs_T_41 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     decode_result_invInputs[2],
     io_inst[5],
     io_inst[6],
     decode_result_invInputs[10],
     io_inst[14]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [5:0]  _decode_result_andMatrixOutputs_T_42 =
    {decode_result_invInputs[0],
     io_inst[4],
     decode_result_invInputs[4],
     io_inst[12],
     decode_result_invInputs[11],
     io_inst[14]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [4:0]  _decode_result_andMatrixOutputs_T_46 =
    {decode_result_invInputs[0],
     decode_result_invInputs[3],
     io_inst[12],
     io_inst[13],
     io_inst[14]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [5:0]  _decode_result_andMatrixOutputs_T_47 =
    {decode_result_invInputs[0],
     io_inst[4],
     io_inst[5],
     io_inst[12],
     io_inst[13],
     io_inst[14]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  wire [31:0] _decode_result_andMatrixOutputs_T_49 =
    {io_inst[0],
     io_inst[1],
     decode_result_invInputs[0],
     decode_result_invInputs[1],
     io_inst[4],
     io_inst[5],
     io_inst[6],
     decode_result_invInputs[5],
     decode_result_invInputs[6],
     decode_result_invInputs[7],
     decode_result_invInputs[8],
     decode_result_invInputs[9],
     decode_result_invInputs[10],
     decode_result_invInputs[11],
     decode_result_invInputs[12],
     decode_result_invInputs[13],
     decode_result_invInputs[14],
     decode_result_invInputs[15],
     decode_result_invInputs[16],
     decode_result_invInputs[17],
     decode_result_invInputs[18],
     io_inst[21],
     decode_result_invInputs[20],
     decode_result_invInputs[21],
     decode_result_invInputs[22],
     decode_result_invInputs[23],
     decode_result_invInputs[24],
     decode_result_invInputs[25],
     io_inst[28],
     io_inst[29],
     decode_result_invInputs[28],
     decode_result_invInputs[29]};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53
  assign io_control_is_csr_inst =
    |{&_decode_result_andMatrixOutputs_T_27, &_decode_result_andMatrixOutputs_T_33};	// src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7
  assign io_control_is_load_inst =
    |{&_decode_result_andMatrixOutputs_T_2, &_decode_result_andMatrixOutputs_T_3};	// src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7
  assign io_control_rg_we =
    |{&_decode_result_andMatrixOutputs_T_2,
      &_decode_result_andMatrixOutputs_T_3,
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[3],
        decode_result_invInputs[4],
        decode_result_invInputs[10]},
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[4],
        decode_result_invInputs[10],
        decode_result_invInputs[11],
        decode_result_invInputs[12],
        decode_result_invInputs[23],
        decode_result_invInputs[24],
        decode_result_invInputs[25],
        decode_result_invInputs[26],
        decode_result_invInputs[27],
        decode_result_invInputs[29]},
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[3],
        decode_result_invInputs[4],
        decode_result_invInputs[24],
        decode_result_invInputs[25],
        decode_result_invInputs[26],
        decode_result_invInputs[27],
        decode_result_invInputs[28],
        decode_result_invInputs[29]},
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[4],
        decode_result_invInputs[23],
        decode_result_invInputs[24],
        decode_result_invInputs[25],
        decode_result_invInputs[26],
        decode_result_invInputs[27],
        decode_result_invInputs[28],
        decode_result_invInputs[29]},
      &{io_inst[0],
        io_inst[1],
        io_inst[2],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[4]},
      &_decode_result_andMatrixOutputs_T_21,
      &_decode_result_andMatrixOutputs_T_22,
      &_decode_result_andMatrixOutputs_T_23,
      &_decode_result_andMatrixOutputs_T_27,
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[3],
        decode_result_invInputs[4],
        io_inst[13]},
      &_decode_result_andMatrixOutputs_T_33,
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[3],
        decode_result_invInputs[4],
        io_inst[14],
        decode_result_invInputs[24],
        decode_result_invInputs[25],
        decode_result_invInputs[26],
        decode_result_invInputs[27],
        decode_result_invInputs[29]},
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[1],
        io_inst[4],
        decode_result_invInputs[4],
        io_inst[12],
        decode_result_invInputs[11],
        io_inst[14],
        decode_result_invInputs[23],
        decode_result_invInputs[24],
        decode_result_invInputs[25],
        decode_result_invInputs[26],
        decode_result_invInputs[27],
        decode_result_invInputs[29]},
      &_decode_result_andMatrixOutputs_T_49};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7
  assign io_control_reg_w_data =
    {&_decode_result_andMatrixOutputs_T,
     |{&_decode_result_andMatrixOutputs_T_4,
       &{io_inst[6], decode_result_invInputs[18]},
       &_decode_result_andMatrixOutputs_T_25,
       &_decode_result_andMatrixOutputs_T_32,
       &_decode_result_andMatrixOutputs_T_40},
     |{&_decode_result_andMatrixOutputs_T_6,
       &_decode_result_andMatrixOutputs_T_7,
       &_decode_result_andMatrixOutputs_T_12,
       &_decode_result_andMatrixOutputs_T_17,
       &_decode_result_andMatrixOutputs_T_25,
       &_decode_result_andMatrixOutputs_T_32,
       &_decode_result_andMatrixOutputs_T_40}};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :66:43
  assign io_control_alu_code =
    {|{&_decode_result_andMatrixOutputs_T_24,
       &_decode_result_andMatrixOutputs_T_35,
       &_decode_result_andMatrixOutputs_T_42,
       &_decode_result_andMatrixOutputs_T_46,
       &_decode_result_andMatrixOutputs_T_47},
     |{&{decode_result_invInputs[0], decode_result_invInputs[2], io_inst[6], io_inst[13]},
       &_decode_result_andMatrixOutputs_T_32,
       &{decode_result_invInputs[0],
         decode_result_invInputs[4],
         io_inst[12],
         io_inst[13],
         decode_result_invInputs[12]},
       &{decode_result_invInputs[0],
         io_inst[4],
         decode_result_invInputs[10],
         io_inst[14]},
       &_decode_result_andMatrixOutputs_T_42},
     |{&_decode_result_andMatrixOutputs_T_24,
       &_decode_result_andMatrixOutputs_T_28,
       &_decode_result_andMatrixOutputs_T_32,
       &{decode_result_invInputs[0],
         decode_result_invInputs[2],
         io_inst[5],
         decode_result_invInputs[11],
         io_inst[14]},
       &{decode_result_invInputs[0],
         io_inst[4],
         decode_result_invInputs[4],
         io_inst[12],
         decode_result_invInputs[11],
         io_inst[30]}},
     |{&_decode_result_andMatrixOutputs_T_18,
       &_decode_result_andMatrixOutputs_T_29,
       &{decode_result_invInputs[0],
         io_inst[4],
         io_inst[5],
         decode_result_invInputs[4],
         decode_result_invInputs[10],
         io_inst[30]}}};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :65:41
  assign io_control_jmp_code =
    {&{io_inst[0],
       io_inst[1],
       decode_result_invInputs[0],
       decode_result_invInputs[1],
       decode_result_invInputs[2],
       io_inst[5],
       io_inst[6],
       io_inst[12],
       io_inst[13],
       io_inst[14]},
     |{&{io_inst[0],
         io_inst[1],
         decode_result_invInputs[0],
         decode_result_invInputs[1],
         decode_result_invInputs[2],
         io_inst[5],
         io_inst[6],
         io_inst[12],
         decode_result_invInputs[11]},
       &_decode_result_andMatrixOutputs_T_41},
     |{&_decode_result_andMatrixOutputs_T_20,
       &_decode_result_andMatrixOutputs_T_21,
       &{io_inst[0],
         io_inst[1],
         decode_result_invInputs[0],
         decode_result_invInputs[1],
         decode_result_invInputs[2],
         io_inst[5],
         io_inst[6],
         io_inst[12],
         decode_result_invInputs[11],
         io_inst[14]},
       &{io_inst[0],
         io_inst[1],
         decode_result_invInputs[0],
         decode_result_invInputs[1],
         decode_result_invInputs[2],
         io_inst[5],
         io_inst[6],
         decode_result_invInputs[10],
         io_inst[13],
         io_inst[14]}},
     |{&_decode_result_andMatrixOutputs_T_20,
       &_decode_result_andMatrixOutputs_T_22,
       &_decode_result_andMatrixOutputs_T_41}};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :64:41
  assign io_control_mem_code =
    {|{&_decode_result_andMatrixOutputs_T_14, io_inst[14]},
     &_decode_result_andMatrixOutputs_T_1};	// src/main/scala/chisel3/util/pla.scala:90:45, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :63:41
  assign io_control_mem_size = io_inst[13:12];	// src/main/scala/chisel3/util/pla.scala:102:36, src/main/scala/componets/ID/Decoder.scala:45:7
  assign io_control_sys_code =
    {|{&_decode_result_andMatrixOutputs_T_23, &_decode_result_andMatrixOutputs_T_49},
     &_decode_result_andMatrixOutputs_T_33,
     |{&_decode_result_andMatrixOutputs_T_27, &_decode_result_andMatrixOutputs_T_49}};	// src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :61:41
  assign io_control_sys_src1 =
    {&{io_inst[0],
       io_inst[1],
       decode_result_invInputs[0],
       decode_result_invInputs[1],
       io_inst[4],
       io_inst[5],
       io_inst[6],
       io_inst[12],
       io_inst[13]},
     &_decode_result_andMatrixOutputs_T_33};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, src/main/scala/componets/ID/Decoder.scala:45:7, :60:41
  assign io_control_rs1_src =
    {|{&{io_inst[2], decode_result_invInputs[3]},
       io_inst[3],
       &_decode_result_andMatrixOutputs_T_40},
     |{&_decode_result_andMatrixOutputs_T,
       &_decode_result_andMatrixOutputs_T_1,
       &_decode_result_andMatrixOutputs_T_4,
       &_decode_result_andMatrixOutputs_T_6,
       &_decode_result_andMatrixOutputs_T_17,
       &_decode_result_andMatrixOutputs_T_18}};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :59:40
  assign io_control_rs2_src =
    {|{&_decode_result_andMatrixOutputs_T,
       &_decode_result_andMatrixOutputs_T_4,
       &_decode_result_andMatrixOutputs_T_6,
       &_decode_result_andMatrixOutputs_T_12,
       &_decode_result_andMatrixOutputs_T_14},
     |{&_decode_result_andMatrixOutputs_T_17,
       &_decode_result_andMatrixOutputs_T_18,
       &_decode_result_andMatrixOutputs_T_32,
       &_decode_result_andMatrixOutputs_T_35,
       &_decode_result_andMatrixOutputs_T_47}};	// src/main/scala/chisel3/util/pla.scala:98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :58:40
  assign io_control_mem_en =
    |{&{io_inst[0],
        io_inst[1],
        decode_result_invInputs[0],
        decode_result_invInputs[1],
        decode_result_invInputs[2],
        io_inst[5],
        decode_result_invInputs[4],
        decode_result_invInputs[10],
        decode_result_invInputs[12]},
      &{io_inst[0],
        io_inst[1],
        decode_result_invInputs[0],
        decode_result_invInputs[1],
        decode_result_invInputs[2],
        io_inst[5],
        decode_result_invInputs[4],
        decode_result_invInputs[11],
        decode_result_invInputs[12]}};	// src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7
  assign io_control_imm_type =
    {|{io_inst[3],
       &_decode_result_andMatrixOutputs_T_12,
       &_decode_result_andMatrixOutputs_T_24,
       &_decode_result_andMatrixOutputs_T_40,
       &_decode_result_andMatrixOutputs_T_42},
     |{&_decode_result_andMatrixOutputs_T_14,
       &_decode_result_andMatrixOutputs_T_18,
       &_decode_result_andMatrixOutputs_T_24,
       &_decode_result_andMatrixOutputs_T_40,
       &_decode_result_andMatrixOutputs_T_42},
     |{&_decode_result_andMatrixOutputs_T,
       &_decode_result_andMatrixOutputs_T_4,
       &_decode_result_andMatrixOutputs_T_7,
       &_decode_result_andMatrixOutputs_T_18,
       &_decode_result_andMatrixOutputs_T_28,
       &_decode_result_andMatrixOutputs_T_29,
       &_decode_result_andMatrixOutputs_T_40,
       &_decode_result_andMatrixOutputs_T_46}};	// src/main/scala/chisel3/util/pla.scala:90:45, :98:{53,70}, :114:{19,36}, src/main/scala/componets/ID/Decoder.scala:45:7, :56:41
  assign io_control_rs1 = io_inst[19:15];	// src/main/scala/componets/ID/Decoder.scala:45:7, :72:31
  assign io_control_rs2 = io_inst[24:20];	// src/main/scala/componets/ID/Decoder.scala:45:7, :73:31
  assign io_control_rd = io_inst[11:7];	// src/main/scala/componets/ID/Decoder.scala:45:7, :71:31
  assign io_control_csr_wad = io_inst[31:20];	// src/main/scala/componets/ID/Decoder.scala:45:7, :74:34
endmodule

