// Generated by CIRCT firtool-1.62.0
module EX(	// src/main/scala/componets/EX/ex.scala:48:7
  input         io_in1_control_is_csr_inst,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_control_is_load_inst,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_control_rg_we,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [2:0]  io_in1_control_reg_w_data,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [3:0]  io_in1_control_alu_code,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_control_jmp_code,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [1:0]  io_in1_control_mem_code,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_control_mem_size,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [2:0]  io_in1_control_sys_code,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [1:0]  io_in1_control_rs1_src,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_control_rs2_src,	// src/main/scala/componets/EX/ex.scala:49:16
  input         io_in1_control_mem_en,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [4:0]  io_in1_control_rd,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [11:0] io_in1_control_csr_wad,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [31:0] io_in1_out_rs1,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_out_rs2,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_out_imm,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_out_mtvec,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_out_mepc,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_out_mstatus,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_out_csr_rd,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_if_data_cur_pc,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_if_data_cur_pc_4,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_if_data_inst,	// src/main/scala/componets/EX/ex.scala:49:16
  input         io_in1_halt_jmp,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [31:0] io_in1_halt_pc,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [1:0]  io_in1_forward1,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_forward2,	// src/main/scala/componets/EX/ex.scala:49:16
  input  [31:0] io_in1_forward_mem,	// src/main/scala/componets/EX/ex.scala:49:16
                io_in1_forward_wb,	// src/main/scala/componets/EX/ex.scala:49:16
  output        io_ctrl_out_control_is_csr_inst,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_control_is_load_inst,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_control_rg_we,	// src/main/scala/componets/EX/ex.scala:49:16
  output [2:0]  io_ctrl_out_control_reg_w_data,	// src/main/scala/componets/EX/ex.scala:49:16
  output [1:0]  io_ctrl_out_control_mem_code,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_control_mem_size,	// src/main/scala/componets/EX/ex.scala:49:16
  output [2:0]  io_ctrl_out_control_sys_code,	// src/main/scala/componets/EX/ex.scala:49:16
  output        io_ctrl_out_control_mem_en,	// src/main/scala/componets/EX/ex.scala:49:16
  output [4:0]  io_ctrl_out_control_rd,	// src/main/scala/componets/EX/ex.scala:49:16
  output [11:0] io_ctrl_out_control_csr_wad,	// src/main/scala/componets/EX/ex.scala:49:16
  output [31:0] io_ctrl_out_out_alu_out,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_out_mem_wd,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_if_data_cur_pc,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_if_data_cur_pc_4,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_if_data_inst,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_csr_data_mtvec,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_csr_data_mepc,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_csr_data_mstatus,	// src/main/scala/componets/EX/ex.scala:49:16
                io_ctrl_out_csr_data_csr_rd,	// src/main/scala/componets/EX/ex.scala:49:16
  output        io_out_notVR_jmp_valid,	// src/main/scala/componets/EX/ex.scala:49:16
  output [31:0] io_out_notVR_jmp_pc	// src/main/scala/componets/EX/ex.scala:49:16
);

  wire             _bru_io_out_jmp_valid;	// src/main/scala/componets/EX/ex.scala:55:21
  wire [31:0]      _alu_io_DataOut;	// src/main/scala/componets/EX/ex.scala:54:21
  wire             _alu_io_Zero;	// src/main/scala/componets/EX/ex.scala:54:21
  wire [3:0][31:0] _GEN =
    {{32'h0}, {io_in1_forward_mem}, {io_in1_forward_wb}, {io_in1_out_rs1}};	// src/main/scala/componets/EX/ex.scala:75:48
  wire [3:0][31:0] _GEN_0 =
    {{32'h0}, {io_in1_forward_mem}, {io_in1_forward_wb}, {io_in1_out_rs2}};	// src/main/scala/componets/EX/ex.scala:75:48, :80:48
  wire [3:0][31:0] _GEN_1 =
    {{io_in1_if_data_cur_pc}, {io_in1_out_imm}, {_GEN[io_in1_forward1]}, {32'h0}};	// src/main/scala/componets/EX/ex.scala:75:48, :86:64
  wire [3:0][31:0] _GEN_2 =
    {{io_in1_if_data_cur_pc}, {io_in1_out_imm}, {_GEN_0[io_in1_forward2]}, {32'h0}};	// src/main/scala/componets/EX/ex.scala:75:48, :80:48, :92:64
  Alu alu (	// src/main/scala/componets/EX/ex.scala:54:21
    .io_AluControl (io_in1_control_alu_code),
    .io_DataIn1    (_GEN_1[io_in1_control_rs1_src]),	// src/main/scala/componets/EX/ex.scala:86:64
    .io_DataIn2    (_GEN_2[io_in1_control_rs2_src]),	// src/main/scala/componets/EX/ex.scala:92:64
    .io_DataOut    (_alu_io_DataOut),
    .io_Zero       (_alu_io_Zero)
  );
  BRU bru (	// src/main/scala/componets/EX/ex.scala:55:21
    .io_in1_is_less   (_alu_io_DataOut[0]),	// src/main/scala/componets/EX/ex.scala:54:21, :105:41
    .io_in1_is_zero   (_alu_io_Zero),	// src/main/scala/componets/EX/ex.scala:54:21
    .io_in1_jmp_code  (io_in1_control_jmp_code),
    .io_in1_halt_jmp  (io_in1_halt_jmp),
    .io_in1_halt_pc   (io_in1_halt_pc),
    .io_in1_cur_pc    (io_in1_if_data_cur_pc),
    .io_in1_imm       (io_in1_out_imm),
    .io_in1_reg_src1  (_GEN[io_in1_forward1]),	// src/main/scala/componets/EX/ex.scala:75:48
    .io_out_jmp_valid (_bru_io_out_jmp_valid),
    .io_out_jmp_pc    (io_out_notVR_jmp_pc)
  );
  ebreak u_ebreak (	// src/main/scala/componets/EX/ex.scala:121:32
    .jmp_valid (_bru_io_out_jmp_valid),	// src/main/scala/componets/EX/ex.scala:55:21
    .inst      (io_in1_if_data_inst),
    .Debug_a0  (io_in1_out_rs1)
  );
  assign io_ctrl_out_control_is_csr_inst = io_in1_control_is_csr_inst;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_is_load_inst = io_in1_control_is_load_inst;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_rg_we = io_in1_control_rg_we;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_reg_w_data = io_in1_control_reg_w_data;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_mem_code = io_in1_control_mem_code;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_mem_size = io_in1_control_mem_size;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_sys_code = io_in1_control_sys_code;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_mem_en = io_in1_control_mem_en;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_rd = io_in1_control_rd;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_control_csr_wad = io_in1_control_csr_wad;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_out_alu_out = _alu_io_DataOut;	// src/main/scala/componets/EX/ex.scala:48:7, :54:21
  assign io_ctrl_out_out_mem_wd = _GEN_0[io_in1_forward2];	// src/main/scala/componets/EX/ex.scala:48:7, :80:48
  assign io_ctrl_out_if_data_cur_pc = io_in1_if_data_cur_pc;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_if_data_cur_pc_4 = io_in1_if_data_cur_pc_4;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_if_data_inst = io_in1_if_data_inst;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_csr_data_mtvec = io_in1_out_mtvec;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_csr_data_mepc = io_in1_out_mepc;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_csr_data_mstatus = io_in1_out_mstatus;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_ctrl_out_csr_data_csr_rd = io_in1_out_csr_rd;	// src/main/scala/componets/EX/ex.scala:48:7
  assign io_out_notVR_jmp_valid = _bru_io_out_jmp_valid;	// src/main/scala/componets/EX/ex.scala:48:7, :55:21
endmodule

