// Generated by CIRCT firtool-1.62.0
/* verilator lint_off UNUSEDSIGNAL */
module ForwardUnit(	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7
  input         io_in_IdEx_control_mem_en,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  input  [31:0] io_in_IdEx_if_data_inst,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  input         io_in_ExMem_control_is_csr_inst,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_in_ExMem_control_is_load_inst,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_in_ExMem_control_rg_we,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  input  [31:0] io_in_ExMem_out_alu_out,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_in_ExMem_if_data_inst,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_in_ExMem_csr_data_csr_rd,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  input         io_in_MemWb_control_rg_we,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  input  [31:0] io_in_MemWb_if_data_inst,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_in_gpr_wd3,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_in_lwsw_data,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  output [1:0]  io_out_forward1,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_out_forward2,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  output [31:0] io_out_forward_mem,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
                io_out_forward_wb,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  output        io_out_forward_lwsw,	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
  output [31:0] io_out_forward_lwsw_data	// src/main/scala/componets/HAZARD/ForwardUnit.scala:30:16
);

  wire _GEN =
    ~io_in_ExMem_control_is_load_inst & io_in_ExMem_control_rg_we
    & (|(io_in_ExMem_if_data_inst[11:7]));	// src/main/scala/componets/HAZARD/ForwardUnit.scala:49:10, :51:{5,28,35}
  wire is_ExMem1 =
    _GEN & io_in_ExMem_if_data_inst[11:7] == io_in_IdEx_if_data_inst[19:15];	// src/main/scala/componets/HAZARD/ForwardUnit.scala:51:{5,28}, :52:{5,37,58}
  wire _GEN_0 = io_in_ExMem_if_data_inst[11:7] == io_in_IdEx_if_data_inst[24:20];	// src/main/scala/componets/HAZARD/ForwardUnit.scala:51:28, :59:{37,58}
  wire is_ExMem2 = _GEN & _GEN_0;	// src/main/scala/componets/HAZARD/ForwardUnit.scala:51:5, :59:{5,37}
  assign io_out_forward1 =
    ~is_ExMem1 & io_in_MemWb_control_rg_we & (|(io_in_MemWb_if_data_inst[11:7]))
    & io_in_MemWb_if_data_inst[11:7] == io_in_IdEx_if_data_inst[19:15]
      ? 2'h1
      : {is_ExMem1, 1'h0};	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7, :44:18, :52:{5,58,67}, :53:22, :65:10, :67:{28,35}, :68:{5,37,67}, :69:22
  assign io_out_forward2 =
    ~is_ExMem2 & io_in_MemWb_control_rg_we & (|(io_in_MemWb_if_data_inst[11:7]))
    & io_in_MemWb_if_data_inst[11:7] == io_in_IdEx_if_data_inst[24:20]
      ? 2'h1
      : {is_ExMem2, 1'h0};	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7, :44:18, :45:18, :52:67, :53:22, :59:{5,58,67}, :60:22, :67:{28,35}, :69:22, :71:10, :74:{5,37,67}, :75:22
  assign io_out_forward_mem =
    io_in_ExMem_control_is_csr_inst
      ? io_in_ExMem_csr_data_csr_rd
      : io_in_ExMem_out_alu_out;	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7, :78:27
  assign io_out_forward_wb = io_in_gpr_wd3;	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7
  assign io_out_forward_lwsw =
    io_in_ExMem_control_is_load_inst & io_in_IdEx_control_mem_en
    & (|(io_in_ExMem_if_data_inst[11:7])) & _GEN_0;	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7, :51:{28,35}, :59:37, :88:5
  assign io_out_forward_lwsw_data = io_in_lwsw_data;	// src/main/scala/componets/HAZARD/ForwardUnit.scala:29:7
endmodule

