// Generated by CIRCT firtool-1.62.0
module GPRegs(	// src/main/scala/componets/ID/gpr.scala:6:7
  input         clock,	// src/main/scala/componets/ID/gpr.scala:6:7
                reset,	// src/main/scala/componets/ID/gpr.scala:6:7
  input  [4:0]  io_A1,	// src/main/scala/componets/ID/gpr.scala:7:16
                io_A2,	// src/main/scala/componets/ID/gpr.scala:7:16
                io_A3,	// src/main/scala/componets/ID/gpr.scala:7:16
  input         io_WE3,	// src/main/scala/componets/ID/gpr.scala:7:16
  input  [31:0] io_WD3,	// src/main/scala/componets/ID/gpr.scala:7:16
  output [31:0] io_RD1,	// src/main/scala/componets/ID/gpr.scala:7:16
                io_RD2	// src/main/scala/componets/ID/gpr.scala:7:16
);

  reg  [31:0]       GPRs_0;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_1;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_2;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_3;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_4;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_5;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_6;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_7;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_8;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_9;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_10;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_11;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_12;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_13;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_14;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_15;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_16;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_17;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_18;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_19;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_20;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_21;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_22;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_23;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_24;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_25;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_26;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_27;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_28;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_29;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_30;	// src/main/scala/componets/ID/gpr.scala:17:23
  reg  [31:0]       GPRs_31;	// src/main/scala/componets/ID/gpr.scala:17:23
  wire [31:0][31:0] _GEN =
    {{GPRs_31},
     {GPRs_30},
     {GPRs_29},
     {GPRs_28},
     {GPRs_27},
     {GPRs_26},
     {GPRs_25},
     {GPRs_24},
     {GPRs_23},
     {GPRs_22},
     {GPRs_21},
     {GPRs_20},
     {GPRs_19},
     {GPRs_18},
     {GPRs_17},
     {GPRs_16},
     {GPRs_15},
     {GPRs_14},
     {GPRs_13},
     {GPRs_12},
     {GPRs_11},
     {GPRs_10},
     {GPRs_9},
     {GPRs_8},
     {GPRs_7},
     {GPRs_6},
     {GPRs_5},
     {GPRs_4},
     {GPRs_3},
     {GPRs_2},
     {GPRs_1},
     {GPRs_0}};	// src/main/scala/componets/ID/gpr.scala:17:23, :20:12
  always @(posedge clock) begin	// src/main/scala/componets/ID/gpr.scala:6:7
    if (reset) begin	// src/main/scala/componets/ID/gpr.scala:6:7
      GPRs_0 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_1 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_2 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_3 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_4 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_5 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_6 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_7 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_8 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_9 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_10 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_11 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_12 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_13 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_14 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_15 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_16 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_17 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_18 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_19 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_20 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_21 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_22 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_23 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_24 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_25 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_26 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_27 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_28 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_29 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_30 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      GPRs_31 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
    end
    else begin	// src/main/scala/componets/ID/gpr.scala:6:7
      automatic logic        _GEN_0 = io_A3 == 5'h0;	// src/main/scala/componets/ID/gpr.scala:24:16
      automatic logic [31:0] _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      _GEN_1 = _GEN_0 ? 32'h0 : io_WE3 ? io_WD3 : _GEN[io_A3];	// src/main/scala/componets/ID/gpr.scala:17:{23,31}, :20:12, :24:16, :25:21, :27:{21,27}
      if (_GEN_0)	// src/main/scala/componets/ID/gpr.scala:24:16
        GPRs_0 <= 32'h0;	// src/main/scala/componets/ID/gpr.scala:17:{23,31}
      if (io_A3 == 5'h1)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_1 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h2)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_2 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h3)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_3 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h4)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_4 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h5)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_5 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h6)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_6 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h7)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_7 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h8)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_8 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h9)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_9 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'hA)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_10 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'hB)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_11 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'hC)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_12 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'hD)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_13 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'hE)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_14 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'hF)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_15 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h10)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_16 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h11)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_17 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h12)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_18 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h13)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_19 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h14)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_20 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h15)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_21 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h16)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_22 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h17)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_23 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h18)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_24 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h19)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_25 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h1A)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_26 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h1B)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_27 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h1C)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_28 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h1D)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_29 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (io_A3 == 5'h1E)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_30 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
      if (&io_A3)	// src/main/scala/componets/ID/gpr.scala:25:21
        GPRs_31 <= _GEN_1;	// src/main/scala/componets/ID/gpr.scala:17:23, :25:21, :27:21
    end
  end // always @(posedge)
  assign io_RD1 = _GEN[io_A1];	// src/main/scala/componets/ID/gpr.scala:6:7, :20:12
  assign io_RD2 = _GEN[io_A2];	// src/main/scala/componets/ID/gpr.scala:6:7, :20:12, :21:12
endmodule

