// Generated by CIRCT firtool-1.62.0
/* verilator lint_off UNUSEDSIGNAL */
module HazardDetectUnit(	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:19:7
  input  [1:0]  io_in_decoder_out_rs1_src,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
                io_in_decoder_out_rs2_src,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
  input  [4:0]  io_in_decoder_out_rs1,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
                io_in_decoder_out_rs2,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
  input  [31:0] io_in_IfId_inst,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
  input         io_in_IdEx_control_is_load_inst,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
  input  [4:0]  io_in_IdEx_control_rd,	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
  output        io_out_is_hazard	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:20:16
);

  assign io_out_is_hazard =
    io_in_IdEx_control_is_load_inst
    & (io_in_IdEx_control_rd == io_in_decoder_out_rs1 & io_in_decoder_out_rs1_src == 2'h1
       | io_in_IdEx_control_rd == io_in_decoder_out_rs2
       & io_in_decoder_out_rs2_src == 2'h1 & io_in_IfId_inst[6:0] != 7'h23);	// src/main/scala/componets/HAZARD/HazardDetectUnit.scala:19:7, :35:48, :36:48, :43:42, :45:{31,45,63}, :46:{31,62,75,81}
endmodule

