// Generated by CIRCT firtool-1.62.0
module ID(	// src/main/scala/componets/ID/id.scala:32:7
  input         clock,	// src/main/scala/componets/ID/id.scala:32:7
                reset,	// src/main/scala/componets/ID/id.scala:32:7
  input  [31:0] io_in1_IfId_cur_pc,	// src/main/scala/componets/ID/id.scala:33:16
                io_in1_IfId_cur_pc_4,	// src/main/scala/componets/ID/id.scala:33:16
                io_in1_IfId_inst,	// src/main/scala/componets/ID/id.scala:33:16
  input  [4:0]  io_in1_gpr_ad3,	// src/main/scala/componets/ID/id.scala:33:16
  input  [31:0] io_in1_gpr_wd3,	// src/main/scala/componets/ID/id.scala:33:16
  input         io_in1_gpr_we3,	// src/main/scala/componets/ID/id.scala:33:16
  input  [11:0] io_in1_csr_wad,	// src/main/scala/componets/ID/id.scala:33:16
  input  [31:0] io_in1_csr_wd,	// src/main/scala/componets/ID/id.scala:33:16
  input         io_in1_csr_we,	// src/main/scala/componets/ID/id.scala:33:16
  input  [2:0]  io_in1_csr_halt_data_sys_code,	// src/main/scala/componets/ID/id.scala:33:16
  input  [31:0] io_in1_csr_halt_data_mstatus_data,	// src/main/scala/componets/ID/id.scala:33:16
                io_in1_csr_halt_data_mcause_data,	// src/main/scala/componets/ID/id.scala:33:16
                io_in1_csr_halt_data_mepc_data,	// src/main/scala/componets/ID/id.scala:33:16
  output        io_ctrl_out_control_is_csr_inst,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_is_load_inst,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_rg_we,	// src/main/scala/componets/ID/id.scala:33:16
  output [2:0]  io_ctrl_out_control_reg_w_data,	// src/main/scala/componets/ID/id.scala:33:16
  output [3:0]  io_ctrl_out_control_alu_code,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_jmp_code,	// src/main/scala/componets/ID/id.scala:33:16
  output [1:0]  io_ctrl_out_control_mem_code,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_mem_size,	// src/main/scala/componets/ID/id.scala:33:16
  output [2:0]  io_ctrl_out_control_sys_code,	// src/main/scala/componets/ID/id.scala:33:16
  output [1:0]  io_ctrl_out_control_sys_src1,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_rs1_src,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_rs2_src,	// src/main/scala/componets/ID/id.scala:33:16
  output        io_ctrl_out_control_mem_en,	// src/main/scala/componets/ID/id.scala:33:16
  output [2:0]  io_ctrl_out_control_imm_type,	// src/main/scala/componets/ID/id.scala:33:16
  output [4:0]  io_ctrl_out_control_rs1,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_rs2,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_control_rd,	// src/main/scala/componets/ID/id.scala:33:16
  output [11:0] io_ctrl_out_control_csr_wad,	// src/main/scala/componets/ID/id.scala:33:16
  output [31:0] io_ctrl_out_out_rs1,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_out_rs2,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_out_imm,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_out_mtvec,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_out_mepc,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_out_mstatus,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_out_csr_rd,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_if_data_cur_pc,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_if_data_cur_pc_4,	// src/main/scala/componets/ID/id.scala:33:16
                io_ctrl_out_if_data_inst	// src/main/scala/componets/ID/id.scala:33:16
);

  wire [1:0] _decoder_io_control_sys_src1;	// src/main/scala/componets/ID/id.scala:39:25
  wire [2:0] _decoder_io_control_imm_type;	// src/main/scala/componets/ID/id.scala:39:25
  Decoder decoder (	// src/main/scala/componets/ID/id.scala:39:25
    .io_inst                 (io_in1_IfId_inst),
    .io_control_is_csr_inst  (io_ctrl_out_control_is_csr_inst),
    .io_control_is_load_inst (io_ctrl_out_control_is_load_inst),
    .io_control_rg_we        (io_ctrl_out_control_rg_we),
    .io_control_reg_w_data   (io_ctrl_out_control_reg_w_data),
    .io_control_alu_code     (io_ctrl_out_control_alu_code),
    .io_control_jmp_code     (io_ctrl_out_control_jmp_code),
    .io_control_mem_code     (io_ctrl_out_control_mem_code),
    .io_control_mem_size     (io_ctrl_out_control_mem_size),
    .io_control_sys_code     (io_ctrl_out_control_sys_code),
    .io_control_sys_src1     (_decoder_io_control_sys_src1),
    .io_control_rs1_src      (io_ctrl_out_control_rs1_src),
    .io_control_rs2_src      (io_ctrl_out_control_rs2_src),
    .io_control_mem_en       (io_ctrl_out_control_mem_en),
    .io_control_imm_type     (_decoder_io_control_imm_type),
    .io_control_rs1          (io_ctrl_out_control_rs1),
    .io_control_rs2          (io_ctrl_out_control_rs2),
    .io_control_rd           (io_ctrl_out_control_rd),
    .io_control_csr_wad      (io_ctrl_out_control_csr_wad)
  );
  IDU idu (	// src/main/scala/componets/ID/id.scala:40:21
    .clock               (clock),
    .reset               (reset),
    .io_in1_sys_code     (io_in1_csr_halt_data_sys_code),
    .io_in1_mstatus_data (io_in1_csr_halt_data_mstatus_data),
    .io_in1_mcause_data  (io_in1_csr_halt_data_mcause_data),
    .io_in1_mepc_data    (io_in1_csr_halt_data_mepc_data),
    .io_in1_inst         (io_in1_IfId_inst),
    .io_in1_gpr_ad3      (io_in1_gpr_ad3),
    .io_in1_gpr_wd3      (io_in1_gpr_wd3),
    .io_in1_gpr_we3      (io_in1_gpr_we3),
    .io_in1_csr_wad      (io_in1_csr_wad),
    .io_in1_csr_wd       (io_in1_csr_wd),
    .io_in1_csr_we       (io_in1_csr_we),
    .io_out_rs1          (io_ctrl_out_out_rs1),
    .io_out_rs2          (io_ctrl_out_out_rs2),
    .io_out_imm          (io_ctrl_out_out_imm),
    .io_out_mtvec        (io_ctrl_out_out_mtvec),
    .io_out_mepc         (io_ctrl_out_out_mepc),
    .io_out_mstatus      (io_ctrl_out_out_mstatus),
    .io_out_csr_rd       (io_ctrl_out_out_csr_rd),
    .io_contrl_sys_src1  (_decoder_io_control_sys_src1),	// src/main/scala/componets/ID/id.scala:39:25
    .io_contrl_imm_type  (_decoder_io_control_imm_type)	// src/main/scala/componets/ID/id.scala:39:25
  );
  assign io_ctrl_out_control_sys_src1 = _decoder_io_control_sys_src1;	// src/main/scala/componets/ID/id.scala:32:7, :39:25
  assign io_ctrl_out_control_imm_type = _decoder_io_control_imm_type;	// src/main/scala/componets/ID/id.scala:32:7, :39:25
  assign io_ctrl_out_if_data_cur_pc = io_in1_IfId_cur_pc;	// src/main/scala/componets/ID/id.scala:32:7
  assign io_ctrl_out_if_data_cur_pc_4 = io_in1_IfId_cur_pc_4;	// src/main/scala/componets/ID/id.scala:32:7
  assign io_ctrl_out_if_data_inst = io_in1_IfId_inst;	// src/main/scala/componets/ID/id.scala:32:7
endmodule

