// Generated by CIRCT firtool-1.62.0
module IDU(	// src/main/scala/componets/ID/idu.scala:51:7
  input         clock,	// src/main/scala/componets/ID/idu.scala:51:7
                reset,	// src/main/scala/componets/ID/idu.scala:51:7
  input  [2:0]  io_in1_sys_code,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [31:0] io_in1_mstatus_data,	// src/main/scala/componets/ID/idu.scala:52:16
                io_in1_mcause_data,	// src/main/scala/componets/ID/idu.scala:52:16
                io_in1_mepc_data,	// src/main/scala/componets/ID/idu.scala:52:16
                io_in1_inst,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [4:0]  io_in1_gpr_ad3,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [31:0] io_in1_gpr_wd3,	// src/main/scala/componets/ID/idu.scala:52:16
  input         io_in1_gpr_we3,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [11:0] io_in1_csr_wad,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [31:0] io_in1_csr_wd,	// src/main/scala/componets/ID/idu.scala:52:16
  input         io_in1_csr_we,	// src/main/scala/componets/ID/idu.scala:52:16
  output [31:0] io_out_rs1,	// src/main/scala/componets/ID/idu.scala:52:16
                io_out_rs2,	// src/main/scala/componets/ID/idu.scala:52:16
                io_out_imm,	// src/main/scala/componets/ID/idu.scala:52:16
                io_out_mtvec,	// src/main/scala/componets/ID/idu.scala:52:16
                io_out_mepc,	// src/main/scala/componets/ID/idu.scala:52:16
                io_out_mstatus,	// src/main/scala/componets/ID/idu.scala:52:16
                io_out_csr_rd,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [1:0]  io_contrl_sys_src1,	// src/main/scala/componets/ID/idu.scala:52:16
  input  [2:0]  io_contrl_imm_type	// src/main/scala/componets/ID/idu.scala:52:16
);

  wire [31:0] _imm_io_immOut;	// src/main/scala/componets/ID/idu.scala:63:21
  wire [31:0] _csr_io_RD;	// src/main/scala/componets/ID/idu.scala:62:21
  wire [31:0] _gpr_io_RD1;	// src/main/scala/componets/ID/idu.scala:61:21
  wire [31:0] _gpr_io_RD2;	// src/main/scala/componets/ID/idu.scala:61:21
  wire [31:0] _GEN = {32{io_contrl_sys_src1[1]}};	// src/main/scala/componets/ID/idu.scala:59:42, :103:22
  GPRegs gpr (	// src/main/scala/componets/ID/idu.scala:61:21
    .clock  (clock),
    .reset  (reset),
    .io_A1  (io_in1_inst[19:15]),	// src/main/scala/componets/ID/idu.scala:69:29
    .io_A2  (io_in1_inst[24:20]),	// src/main/scala/componets/ID/idu.scala:70:29
    .io_A3  (io_in1_gpr_ad3),
    .io_WE3 (io_in1_gpr_we3),
    .io_WD3 (io_in1_gpr_wd3),
    .io_RD1 (_gpr_io_RD1),
    .io_RD2 (_gpr_io_RD2)
  );
  CSRegs csr (	// src/main/scala/componets/ID/idu.scala:62:21
    .clock                     (clock),
    .reset                     (reset),
    .io_WAD                    (io_in1_csr_wad),
    .io_WE                     (io_in1_csr_we),
    .io_AD                     (io_in1_inst[31:20]),	// src/main/scala/componets/ID/idu.scala:80:29
    .io_WD                     (io_in1_csr_wd),
    .io_RD                     (_csr_io_RD),
    .io_mtvec                  (io_out_mtvec),
    .io_mepc                   (io_out_mepc),
    .io_mstatus                (io_out_mstatus),
    .io_halt_data_sys_code     (io_in1_sys_code),
    .io_halt_data_mstatus_data (io_in1_mstatus_data),
    .io_halt_data_mcause_data  (io_in1_mcause_data),
    .io_halt_data_mepc_data    (io_in1_mepc_data)
  );
  ImmExt imm (	// src/main/scala/componets/ID/idu.scala:63:21
    .io_immControl (io_contrl_imm_type),
    .io_inst       (io_in1_inst),
    .io_immOut     (_imm_io_immOut)
  );
  assign io_out_rs1 = _GEN ^ _gpr_io_RD1;	// src/main/scala/componets/ID/idu.scala:51:7, :61:21, :103:22
  assign io_out_rs2 = io_contrl_sys_src1[0] ? _csr_io_RD : _gpr_io_RD2;	// src/main/scala/componets/ID/idu.scala:51:7, :58:38, :61:21, :62:21, :104:22
  assign io_out_imm = _GEN ^ _imm_io_immOut;	// src/main/scala/componets/ID/idu.scala:51:7, :63:21, :103:22, :105:22
  assign io_out_csr_rd = _csr_io_RD;	// src/main/scala/componets/ID/idu.scala:51:7, :62:21
endmodule

