// Generated by CIRCT firtool-1.62.0
module IF(	// src/main/scala/componets/IF/if.scala:20:7
  input         clock,	// src/main/scala/componets/IF/if.scala:20:7
                reset,	// src/main/scala/componets/IF/if.scala:20:7
                io_in1_jmp_valid,	// src/main/scala/componets/IF/if.scala:21:16
  input  [31:0] io_in1_jmp_pc,	// src/main/scala/componets/IF/if.scala:21:16
  input         io_in1_stall,	// src/main/scala/componets/IF/if.scala:21:16
  output [31:0] io_out_cur_pc,	// src/main/scala/componets/IF/if.scala:21:16
                io_out_cur_pc_4,	// src/main/scala/componets/IF/if.scala:21:16
                io_out_inst	// src/main/scala/componets/IF/if.scala:21:16
);

  reg  [31:0] pcReg;	// src/main/scala/componets/IF/if.scala:28:24
  wire [31:0] _io_out_cur_pc_4_T = pcReg + 32'h4;	// src/main/scala/componets/IF/if.scala:28:24, :35:61
  always @(posedge clock) begin	// src/main/scala/componets/IF/if.scala:20:7
    if (reset)	// src/main/scala/componets/IF/if.scala:20:7
      pcReg <= 32'h7FFFFFFC;	// src/main/scala/componets/IF/if.scala:28:24
    else if (io_in1_stall) begin	// src/main/scala/componets/IF/if.scala:21:16
    end
    else if (io_in1_jmp_valid)	// src/main/scala/componets/IF/if.scala:21:16
      pcReg <= io_in1_jmp_pc;	// src/main/scala/componets/IF/if.scala:28:24
    else	// src/main/scala/componets/IF/if.scala:21:16
      pcReg <= _io_out_cur_pc_4_T;	// src/main/scala/componets/IF/if.scala:28:24, :35:61
  end // always @(posedge)
  IFU ifu (	// src/main/scala/componets/IF/if.scala:32:21
    .clock   (clock),
    .io_pc
      (io_in1_stall ? pcReg : io_in1_jmp_valid ? io_in1_jmp_pc : _io_out_cur_pc_4_T),	// src/main/scala/componets/IF/if.scala:28:24, :35:{21,61}, :42:22
    .io_inst (io_out_inst)
  );
  assign io_out_cur_pc = pcReg;	// src/main/scala/componets/IF/if.scala:20:7, :28:24
  assign io_out_cur_pc_4 = _io_out_cur_pc_4_T;	// src/main/scala/componets/IF/if.scala:20:7, :35:61
endmodule

