// Generated by CIRCT firtool-1.62.0
module IFU(	// src/main/scala/componets/IF/ifu.scala:6:7
  input         clock,	// src/main/scala/componets/IF/ifu.scala:6:7
  input  [31:0] io_pc,	// src/main/scala/componets/IF/ifu.scala:7:16
  output [31:0] io_inst	// src/main/scala/componets/IF/ifu.scala:7:16
);

  imem instMem(
    .clock 	(clock  ),
    .Addr  	(io_pc  ),
    .Inst  	(io_inst)
  );
  
endmodule

