// Generated by CIRCT firtool-1.62.0
module ImmExt(	// src/main/scala/componets/ID/ImmExt.scala:7:7
  input  [2:0]  io_immControl,	// src/main/scala/componets/ID/ImmExt.scala:8:16
  /* verilator lint_off UNUSEDSIGNAL */
  input  [31:0] io_inst,	// src/main/scala/componets/ID/ImmExt.scala:8:16
  output [31:0] io_immOut	// src/main/scala/componets/ID/ImmExt.scala:8:16
);

  wire [19:0]      immTrans = {20{io_inst[31]}};	// src/main/scala/componets/ID/ImmExt.scala:15:{21,32}
  wire [7:0][31:0] _GEN =
    {{{27'h0, io_inst[19:15]}},
     {{27'h0, io_inst[24:20]}},
     {{{12{io_inst[31]}}, io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}},
     {{io_inst[31:12], 12'h0}},
     {{{20{io_inst[31]}}, io_inst[7], io_inst[30:25], io_inst[11:8], 1'h0}},
     {{immTrans, io_inst[31:25], io_inst[11:7]}},
     {{immTrans, io_inst[31:20]}},
     {32'h0}};	// src/main/scala/componets/ID/ImmExt.scala:15:{21,32}, :17:15, :18:26, :19:{33,39,57}, :20:{33,39,57,73}, :21:{33,70,82,98}, :22:{33,39,48,63,79,92}, :23:{33,39,47,59}, :24:{37,43,48,65}, :25:{35,41,64}
  assign io_immOut = _GEN[io_immControl];	// src/main/scala/componets/ID/ImmExt.scala:7:7, :17:15, :18:26, :19:33, :20:33, :21:33, :22:33, :23:33, :24:37, :25:35
endmodule

