// Generated by CIRCT firtool-1.62.0
module IRU(	// src/main/scala/componets/WB/iru.scala:23:7
  input  [2:0]  io_in1_sys_code,	// src/main/scala/componets/WB/iru.scala:24:16
  /* verilator lint_off UNUSEDSIGNAL */
  input  [31:0] io_in1_mstatus,	// src/main/scala/componets/WB/iru.scala:24:16
                io_in1_mepc,	// src/main/scala/componets/WB/iru.scala:24:16
                io_in1_mtvec,	// src/main/scala/componets/WB/iru.scala:24:16
                io_in1_cur_pc,	// src/main/scala/componets/WB/iru.scala:24:16
  output [31:0] io_out_halt_pc,	// src/main/scala/componets/WB/iru.scala:24:16
  output        io_out_halt_jmp,	// src/main/scala/componets/WB/iru.scala:24:16
  output [31:0] io_out_mstatus_data,	// src/main/scala/componets/WB/iru.scala:24:16
                io_out_mcause_data,	// src/main/scala/componets/WB/iru.scala:24:16
                io_out_mepc_data,	// src/main/scala/componets/WB/iru.scala:24:16
  output        io_out_csr_we	// src/main/scala/componets/WB/iru.scala:24:16
);

  wire io_out_csr_we_0 =
    io_in1_sys_code == 3'h3 | io_in1_sys_code == 3'h1 | io_in1_sys_code == 3'h2;	// src/main/scala/componets/WB/iru.scala:38:{25,62,83,99}
  wire _GEN = io_in1_sys_code == 3'h4;	// src/main/scala/componets/WB/iru.scala:41:29
  wire _GEN_0 = io_out_csr_we_0 | ~_GEN;	// src/main/scala/componets/WB/iru.scala:35:21, :38:{83,121}, :41:{29,50}
  wire _GEN_1 = io_in1_sys_code == 3'h5;	// src/main/scala/componets/WB/iru.scala:48:29
  assign io_out_halt_pc =
    io_out_csr_we_0 ? 32'h0 : _GEN ? io_in1_mtvec : _GEN_1 ? io_in1_mepc : 32'h0;	// src/main/scala/componets/WB/iru.scala:23:7, :33:17, :38:{83,121}, :41:{29,50}, :42:21, :48:{29,49}, :49:21
  assign io_out_halt_jmp = ~io_out_csr_we_0 & (_GEN | _GEN_1);	// src/main/scala/componets/WB/iru.scala:23:7, :38:{83,121}, :39:22, :41:{29,50}, :43:22, :48:{29,49}
  assign io_out_mstatus_data =
    io_out_csr_we_0
      ? 32'h0
      : _GEN
          ? 32'h1800
          : _GEN_1
              ? {io_in1_mstatus[31:13],
                 2'h0,
                 io_in1_mstatus[10:8],
                 1'h1,
                 io_in1_mstatus[6:4],
                 io_in1_mstatus[7],
                 io_in1_mstatus[2:0]}
              : 32'h0;	// src/main/scala/componets/WB/iru.scala:23:7, :33:17, :34:22, :38:{62,83,121}, :41:{29,50}, :44:25, :48:{29,49}, :51:{25,31,43,74,104,122,138}
  assign io_out_mcause_data = _GEN_0 ? 32'h0 : 32'hB;	// src/main/scala/componets/WB/iru.scala:23:7, :33:17, :35:21, :38:121, :41:50, :45:25
  assign io_out_mepc_data = _GEN_0 ? 32'h0 : io_in1_cur_pc;	// src/main/scala/componets/WB/iru.scala:23:7, :33:17, :35:21, :36:19, :38:121, :41:50
  assign io_out_csr_we = io_out_csr_we_0;	// src/main/scala/componets/WB/iru.scala:23:7, :38:83
endmodule

