// Generated by CIRCT firtool-1.62.0
module LSU(	// src/main/scala/componets/MEM/lsu.scala:38:7
  input         clock,	// src/main/scala/componets/MEM/lsu.scala:38:7
                io_in1_control_is_csr_inst,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_control_is_load_inst,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_control_rg_we,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [2:0]  io_in1_control_reg_w_data,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [1:0]  io_in1_control_mem_code,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_control_mem_size,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [2:0]  io_in1_control_sys_code,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [4:0]  io_in1_control_rd,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [11:0] io_in1_control_csr_wad,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [31:0] io_in1_out_alu_out,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_if_data_cur_pc,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_if_data_cur_pc_4,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_if_data_inst,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_csr_data_mtvec,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_csr_data_mepc,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_csr_data_mstatus,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_csr_data_csr_rd,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input         io_in1_forward_lwsw,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [31:0] io_in1_forward_lwsw_data,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [1:0]  io_in1_next_control_mem_size,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input         io_in1_next_control_mem_en,	// src/main/scala/componets/MEM/lsu.scala:39:16
  input  [31:0] io_in1_next_alu_out,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_in1_next_mem_wb,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output        io_ctrl_out_control_is_csr_inst,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_control_is_load_inst,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_control_rg_we,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output [2:0]  io_ctrl_out_control_reg_w_data,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output [1:0]  io_ctrl_out_control_mem_code,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_control_mem_size,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output [2:0]  io_ctrl_out_control_sys_code,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output [4:0]  io_ctrl_out_control_rd,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output [11:0] io_ctrl_out_control_csr_wad,	// src/main/scala/componets/MEM/lsu.scala:39:16
  output [31:0] io_ctrl_out_out_mem_out,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_out_fu_alu,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_if_data_cur_pc,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_if_data_cur_pc_4,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_if_data_inst,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_csr_data_mtvec,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_csr_data_mepc,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_csr_data_mstatus,	// src/main/scala/componets/MEM/lsu.scala:39:16
                io_ctrl_out_csr_data_csr_rd,	// src/main/scala/componets/MEM/lsu.scala:39:16
  //---------------------------------将dmem和cpu主体部分分离-------------------------------------
  output wire  [31:0] Addr_cpu,
  output wire  [31:0] WD_cpu,
  output wire         WE_cpu,
  output wire  [1:0]  LEN_cpu,
  input        [31:0] dout_cpu
  //--------------------------------------------------------------------------------------------
);

  assign io_ctrl_out_control_is_csr_inst = io_in1_control_is_csr_inst;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_is_load_inst = io_in1_control_is_load_inst;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_rg_we = io_in1_control_rg_we;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_reg_w_data = io_in1_control_reg_w_data;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_mem_code = io_in1_control_mem_code;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_mem_size = io_in1_control_mem_size;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_sys_code = io_in1_control_sys_code;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_rd = io_in1_control_rd;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_control_csr_wad = io_in1_control_csr_wad;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_out_mem_out =
    io_in1_control_mem_size == 2'h0
      ? {{24{io_in1_control_mem_code[0] & dout_cpu[7]}}, dout_cpu[7:0]}
      : io_in1_control_mem_size == 2'h1
          ? {{16{io_in1_control_mem_code[0] & dout_cpu[15]}}, dout_cpu[15:0]}
          : dout_cpu;	// src/main/scala/componets/MEM/lsu.scala:38:7, :43:21, :61:33, :62:{41,47,68,82,87,98,110,122}, :63:{41,47,68,82,87,98,111,123}
  assign io_ctrl_out_out_fu_alu = io_in1_out_alu_out;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_if_data_cur_pc = io_in1_if_data_cur_pc;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_if_data_cur_pc_4 = io_in1_if_data_cur_pc_4;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_if_data_inst = io_in1_if_data_inst;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_csr_data_mtvec = io_in1_csr_data_mtvec;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_csr_data_mepc = io_in1_csr_data_mepc;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_csr_data_mstatus = io_in1_csr_data_mstatus;	// src/main/scala/componets/MEM/lsu.scala:38:7
  assign io_ctrl_out_csr_data_csr_rd = io_in1_csr_data_csr_rd;	// src/main/scala/componets/MEM/lsu.scala:38:7

  //---------------------------------将dmem和cpu主体部分分离------------------------------------------

  assign  Addr_cpu  = io_in1_next_alu_out;
  assign  WD_cpu    = io_in1_forward_lwsw ? io_in1_forward_lwsw_data : io_in1_next_mem_wb;
  assign  WE_cpu    = io_in1_next_control_mem_en;
  assign  LEN_cpu   = io_in1_next_control_mem_size;
endmodule

