// Generated by CIRCT firtool-1.62.0
module PipelineControlUnit(	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7
  input         io_in_hazard_is_hazard,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
                io_in_redirect_redirect_valid,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
  input  [31:0] io_in_redirect_redirect_target,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
  output        io_out_pc_stall,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
                io_out_pc_redirect_valid,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
  output [31:0] io_out_pc_redirect_target,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
  output        io_out_if_id_stall,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
                io_out_if_id_flush,	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
                io_out_id_ex_flush	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:32:14
);

  wire io_out_pc_stall_0 = ~io_in_redirect_redirect_valid & io_in_hazard_is_hazard;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:43:29, :56:32, :61:31
  assign io_out_pc_stall = io_out_pc_stall_0;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7, :43:29, :56:32, :61:31
  assign io_out_pc_redirect_valid = io_in_redirect_redirect_valid;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7
  assign io_out_pc_redirect_target =
    io_in_redirect_redirect_valid ? io_in_redirect_redirect_target : 32'h0;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7, :45:29, :56:32, :58:28
  assign io_out_if_id_stall = io_out_pc_stall_0;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7, :43:29, :56:32, :61:31
  assign io_out_if_id_flush = io_in_redirect_redirect_valid;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7
  assign io_out_id_ex_flush = io_in_redirect_redirect_valid | io_in_hazard_is_hazard;	// src/main/scala/componets/HAZARD/PipelineControlUnit.scala:31:7, :56:32, :60:28, :61:31
endmodule

