// Generated by CIRCT firtool-1.62.0
module PipelineReg(	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
  input         clock,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
                reset,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
  input  [31:0] io_in_cur_pc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_cur_pc_4,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input         io_ctrl_stall,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_ctrl_flush,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [31:0] io_out_cur_pc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_cur_pc_4,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_inst	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
);

  reg [31:0] reg_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  always @(posedge clock) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
    if (reset) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_cur_pc <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/IF_ID.scala:11:22
      reg_cur_pc_4 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/IF_ID.scala:11:22
      reg_inst <= 32'h13;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/IF_ID.scala:13:12
    end
    else if (io_ctrl_flush) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
      reg_cur_pc <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/IF_ID.scala:11:22
      reg_cur_pc_4 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/IF_ID.scala:11:22
      reg_inst <= 32'h13;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/IF_ID.scala:13:12
    end
    else if (io_ctrl_stall) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
    end
    else begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
      reg_cur_pc <= io_in_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_cur_pc_4 <= io_in_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_inst <= io_in_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
    end
  end // always @(posedge)
  assign io_out_cur_pc = reg_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_cur_pc_4 = reg_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_inst = reg_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
endmodule

