// Generated by CIRCT firtool-1.62.0
module PipelineReg_1(	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
  input         clock,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
                reset,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
                io_in_control_is_csr_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_is_load_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_rg_we,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [2:0]  io_in_control_reg_w_data,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [3:0]  io_in_control_alu_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_jmp_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [1:0]  io_in_control_mem_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_mem_size,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [2:0]  io_in_control_sys_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [1:0]  io_in_control_sys_src1,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_rs1_src,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_rs2_src,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input         io_in_control_mem_en,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [2:0]  io_in_control_imm_type,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [4:0]  io_in_control_rs1,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_rs2,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [11:0] io_in_control_csr_wad,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [31:0] io_in_out_rs1,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_out_rs2,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_out_imm,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_out_mtvec,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_out_mepc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_out_mstatus,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_out_csr_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_if_data_cur_pc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_if_data_cur_pc_4,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_if_data_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input         io_ctrl_flush,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output        io_out_control_is_csr_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_is_load_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_rg_we,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [2:0]  io_out_control_reg_w_data,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [3:0]  io_out_control_alu_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_jmp_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [1:0]  io_out_control_mem_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_mem_size,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [2:0]  io_out_control_sys_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [1:0]  io_out_control_sys_src1,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_rs1_src,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_rs2_src,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output        io_out_control_mem_en,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [2:0]  io_out_control_imm_type,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [4:0]  io_out_control_rs1,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_rs2,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [11:0] io_out_control_csr_wad,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [31:0] io_out_out_rs1,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_out_rs2,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_out_imm,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_out_mtvec,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_out_mepc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_out_mstatus,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_out_csr_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_if_data_cur_pc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_if_data_cur_pc_4,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_if_data_inst	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
);

  reg        reg_control_is_csr_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg        reg_control_is_load_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg        reg_control_rg_we;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [2:0]  reg_control_reg_w_data;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [3:0]  reg_control_alu_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [3:0]  reg_control_jmp_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_mem_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_mem_size;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [2:0]  reg_control_sys_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_sys_src1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_rs1_src;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_rs2_src;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg        reg_control_mem_en;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [2:0]  reg_control_imm_type;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [4:0]  reg_control_rs1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [4:0]  reg_control_rs2;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [4:0]  reg_control_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [11:0] reg_control_csr_wad;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_rs1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_rs2;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_imm;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_mtvec;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_mepc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_mstatus;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_csr_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_if_data_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_if_data_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_if_data_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  always @(posedge clock) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
    if (reset) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_control_is_csr_inst <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_is_load_inst <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_rg_we <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_reg_w_data <= 3'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_alu_code <= 4'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_jmp_code <= 4'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_mem_code <= 2'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_mem_size <= 2'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_sys_code <= 3'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_sys_src1 <= 2'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_rs1_src <= 2'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_rs2_src <= 2'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_mem_en <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_imm_type <= 3'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_rs1 <= 5'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_rs2 <= 5'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_rd <= 5'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_control_csr_wad <= 12'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_rs1 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_rs2 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_imm <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_mtvec <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_mepc <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_mstatus <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_out_csr_rd <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_if_data_cur_pc <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_if_data_cur_pc_4 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :28:22
      reg_if_data_inst <= 32'h13;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :30:20
    end
    else begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_control_is_csr_inst <= ~io_ctrl_flush & io_in_control_is_csr_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31
      reg_control_is_load_inst <= ~io_ctrl_flush & io_in_control_is_load_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31
      reg_control_rg_we <= ~io_ctrl_flush & io_in_control_rg_we;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31
      reg_control_reg_w_data <= io_ctrl_flush ? 3'h0 : io_in_control_reg_w_data;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_alu_code <= io_ctrl_flush ? 4'h0 : io_in_control_alu_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_jmp_code <= io_ctrl_flush ? 4'h0 : io_in_control_jmp_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_mem_code <= io_ctrl_flush ? 2'h0 : io_in_control_mem_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_mem_size <= io_ctrl_flush ? 2'h0 : io_in_control_mem_size;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_sys_code <= io_ctrl_flush ? 3'h0 : io_in_control_sys_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_sys_src1 <= io_ctrl_flush ? 2'h0 : io_in_control_sys_src1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_rs1_src <= io_ctrl_flush ? 2'h0 : io_in_control_rs1_src;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_rs2_src <= io_ctrl_flush ? 2'h0 : io_in_control_rs2_src;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_mem_en <= ~io_ctrl_flush & io_in_control_mem_en;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31
      reg_control_imm_type <= io_ctrl_flush ? 3'h0 : io_in_control_imm_type;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_rs1 <= io_ctrl_flush ? 5'h0 : io_in_control_rs1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_rs2 <= io_ctrl_flush ? 5'h0 : io_in_control_rs2;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_rd <= io_ctrl_flush ? 5'h0 : io_in_control_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_control_csr_wad <= io_ctrl_flush ? 12'h0 : io_in_control_csr_wad;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_rs1 <= io_ctrl_flush ? 32'h0 : io_in_out_rs1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_rs2 <= io_ctrl_flush ? 32'h0 : io_in_out_rs2;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_imm <= io_ctrl_flush ? 32'h0 : io_in_out_imm;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_mtvec <= io_ctrl_flush ? 32'h0 : io_in_out_mtvec;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_mepc <= io_ctrl_flush ? 32'h0 : io_in_out_mepc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_mstatus <= io_ctrl_flush ? 32'h0 : io_in_out_mstatus;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_out_csr_rd <= io_ctrl_flush ? 32'h0 : io_in_out_csr_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_if_data_cur_pc <= io_ctrl_flush ? 32'h0 : io_in_if_data_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_if_data_cur_pc_4 <= io_ctrl_flush ? 32'h0 : io_in_if_data_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :28:22
      reg_if_data_inst <= io_ctrl_flush ? 32'h13 : io_in_if_data_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, :15:24, :16:13, :17:31, :30:20
    end
  end // always @(posedge)
  assign io_out_control_is_csr_inst = reg_control_is_csr_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_is_load_inst = reg_control_is_load_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rg_we = reg_control_rg_we;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_reg_w_data = reg_control_reg_w_data;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_alu_code = reg_control_alu_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_jmp_code = reg_control_jmp_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_mem_code = reg_control_mem_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_mem_size = reg_control_mem_size;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_sys_code = reg_control_sys_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_sys_src1 = reg_control_sys_src1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rs1_src = reg_control_rs1_src;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rs2_src = reg_control_rs2_src;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_mem_en = reg_control_mem_en;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_imm_type = reg_control_imm_type;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rs1 = reg_control_rs1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rs2 = reg_control_rs2;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rd = reg_control_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_csr_wad = reg_control_csr_wad;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_rs1 = reg_out_rs1;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_rs2 = reg_out_rs2;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_imm = reg_out_imm;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_mtvec = reg_out_mtvec;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_mepc = reg_out_mepc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_mstatus = reg_out_mstatus;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_csr_rd = reg_out_csr_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_if_data_cur_pc = reg_if_data_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_if_data_cur_pc_4 = reg_if_data_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_if_data_inst = reg_if_data_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
endmodule

