// Generated by CIRCT firtool-1.62.0
module PipelineReg_4(	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
  input         clock,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
                reset,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
  input  [31:0] io_in_gpr_wd3,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [31:0] io_out_gpr_wd3	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
);

  reg [31:0] reg_gpr_wd3;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  always @(posedge clock) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
    if (reset)	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_gpr_wd3 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:24:22
    else	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_gpr_wd3 <= io_in_gpr_wd3;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  end // always @(posedge)
  assign io_out_gpr_wd3 = reg_gpr_wd3;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
endmodule

