// Generated by CIRCT firtool-1.62.0
module PipelineReg_2(	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
  input         clock,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
                reset,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
                io_in_control_is_csr_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_is_load_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_rg_we,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [2:0]  io_in_control_reg_w_data,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [1:0]  io_in_control_mem_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_control_mem_size,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [2:0]  io_in_control_sys_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [4:0]  io_in_control_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [11:0] io_in_control_csr_wad,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  input  [31:0] io_in_out_alu_out,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_if_data_cur_pc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_if_data_cur_pc_4,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_if_data_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_csr_data_mtvec,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_csr_data_mepc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_csr_data_mstatus,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_in_csr_data_csr_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output        io_out_control_is_csr_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_is_load_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_rg_we,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [2:0]  io_out_control_reg_w_data,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [1:0]  io_out_control_mem_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_control_mem_size,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [2:0]  io_out_control_sys_code,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [4:0]  io_out_control_rd,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [11:0] io_out_control_csr_wad,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
  output [31:0] io_out_out_alu_out,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_if_data_cur_pc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_if_data_cur_pc_4,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_if_data_inst,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_csr_data_mtvec,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_csr_data_mepc,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_csr_data_mstatus,	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
                io_out_csr_data_csr_rd	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16
);

  reg        reg_control_is_csr_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg        reg_control_is_load_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg        reg_control_rg_we;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [2:0]  reg_control_reg_w_data;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_mem_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [1:0]  reg_control_mem_size;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [2:0]  reg_control_sys_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [4:0]  reg_control_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [11:0] reg_control_csr_wad;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_out_alu_out;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_if_data_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_if_data_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_if_data_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_csr_data_mtvec;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_csr_data_mepc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_csr_data_mstatus;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  reg [31:0] reg_csr_data_csr_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
  always @(posedge clock) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
    if (reset) begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_control_is_csr_inst <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16, :13:22
      reg_control_is_load_inst <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16, :13:22
      reg_control_rg_we <= 1'h0;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:7:16, :13:22
      reg_control_reg_w_data <= 3'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_control_mem_code <= 2'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_control_mem_size <= 2'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_control_sys_code <= 3'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_control_rd <= 5'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_control_csr_wad <= 12'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_out_alu_out <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_if_data_cur_pc <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_if_data_cur_pc_4 <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_if_data_inst <= 32'h13;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:12:20, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:12:20
      reg_csr_data_mtvec <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_csr_data_mepc <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_csr_data_mstatus <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
      reg_csr_data_csr_rd <= 32'h0;	// src/main/scala/componets/Pipeline_regs/EX_MEM.scala:10:22, src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22, src/main/scala/componets/Pipeline_regs/MEM_WB.scala:10:22
    end
    else begin	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7
      reg_control_is_csr_inst <= io_in_control_is_csr_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_is_load_inst <= io_in_control_is_load_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_rg_we <= io_in_control_rg_we;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_reg_w_data <= io_in_control_reg_w_data;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_mem_code <= io_in_control_mem_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_mem_size <= io_in_control_mem_size;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_sys_code <= io_in_control_sys_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_rd <= io_in_control_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_control_csr_wad <= io_in_control_csr_wad;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_out_alu_out <= io_in_out_alu_out;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_if_data_cur_pc <= io_in_if_data_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_if_data_cur_pc_4 <= io_in_if_data_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_if_data_inst <= io_in_if_data_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_csr_data_mtvec <= io_in_csr_data_mtvec;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_csr_data_mepc <= io_in_csr_data_mepc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_csr_data_mstatus <= io_in_csr_data_mstatus;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
      reg_csr_data_csr_rd <= io_in_csr_data_csr_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:13:22
    end
  end // always @(posedge)
  assign io_out_control_is_csr_inst = reg_control_is_csr_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_is_load_inst = reg_control_is_load_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rg_we = reg_control_rg_we;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_reg_w_data = reg_control_reg_w_data;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_mem_code = reg_control_mem_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_mem_size = reg_control_mem_size;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_sys_code = reg_control_sys_code;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_rd = reg_control_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_control_csr_wad = reg_control_csr_wad;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_out_alu_out = reg_out_alu_out;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_if_data_cur_pc = reg_if_data_cur_pc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_if_data_cur_pc_4 = reg_if_data_cur_pc_4;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_if_data_inst = reg_if_data_inst;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_csr_data_mtvec = reg_csr_data_mtvec;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_csr_data_mepc = reg_csr_data_mepc;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_csr_data_mstatus = reg_csr_data_mstatus;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
  assign io_out_csr_data_csr_rd = reg_csr_data_csr_rd;	// src/main/scala/componets/Pipeline_regs/ID_EX.scala:6:7, :13:22
endmodule

