// Generated by CIRCT firtool-1.62.0
module vmem(	// src/main/scala/componets/MEM/memfile.scala:19:7
  input         io_clock,	// src/main/scala/componets/MEM/memfile.scala:20:14
  input  [31:0] io_Addr,	// src/main/scala/componets/MEM/memfile.scala:20:14
                io_WD,	// src/main/scala/componets/MEM/memfile.scala:20:14
  input         io_WE,	// src/main/scala/componets/MEM/memfile.scala:20:14
  input  [1:0]  io_LEN,	// src/main/scala/componets/MEM/memfile.scala:20:14
  output [31:0] io_RD	// src/main/scala/componets/MEM/memfile.scala:20:14
);

  dmem dataMem(
    .clock (io_clock),
    .Addr  (io_Addr),
    .WD    (io_WD),
    .WE    (io_WE),
    .LEN   (io_LEN),
    .Inst  (io_RD)
  );
  
endmodule

