// Generated by CIRCT firtool-1.62.0
module WB(	// src/main/scala/componets/WB/wb.scala:19:7
  input         io_in1_control_rg_we,	// src/main/scala/componets/WB/wb.scala:20:16
  input  [2:0]  io_in1_control_reg_w_data,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_control_sys_code,	// src/main/scala/componets/WB/wb.scala:20:16
  input  [31:0] io_in1_out_mem_out,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_out_fu_alu,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_if_data_cur_pc,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_if_data_cur_pc_4,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_csr_data_mtvec,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_csr_data_mepc,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_csr_data_mstatus,	// src/main/scala/componets/WB/wb.scala:20:16
                io_in1_csr_data_csr_rd,	// src/main/scala/componets/WB/wb.scala:20:16
  output [31:0] io_ctrl_out_halt_pc,	// src/main/scala/componets/WB/wb.scala:20:16
  output        io_ctrl_out_halt_jmp,	// src/main/scala/componets/WB/wb.scala:20:16
  output [31:0] io_ctrl_out_mstatus_data,	// src/main/scala/componets/WB/wb.scala:20:16
                io_ctrl_out_mcause_data,	// src/main/scala/componets/WB/wb.scala:20:16
                io_ctrl_out_mepc_data,	// src/main/scala/componets/WB/wb.scala:20:16
  output        io_ctrl_out_csr_we,	// src/main/scala/componets/WB/wb.scala:20:16
  output [31:0] io_ctrl_out_gpr_wd3,	// src/main/scala/componets/WB/wb.scala:20:16
  output        io_ctrl_out_gpr_we3,	// src/main/scala/componets/WB/wb.scala:20:16
  output [2:0]  io_ctrl_out_sys_code,	// src/main/scala/componets/WB/wb.scala:20:16
  output [31:0] io_ctrl_out_csr_wd	// src/main/scala/componets/WB/wb.scala:20:16
);

  IRU iru (	// src/main/scala/componets/WB/wb.scala:24:21
    .io_in1_sys_code     (io_in1_control_sys_code),
    .io_in1_mstatus      (io_in1_csr_data_mstatus),
    .io_in1_mepc         (io_in1_csr_data_mepc),
    .io_in1_mtvec        (io_in1_csr_data_mtvec),
    .io_in1_cur_pc       (io_in1_if_data_cur_pc),
    .io_out_halt_pc      (io_ctrl_out_halt_pc),
    .io_out_halt_jmp     (io_ctrl_out_halt_jmp),
    .io_out_mstatus_data (io_ctrl_out_mstatus_data),
    .io_out_mcause_data  (io_ctrl_out_mcause_data),
    .io_out_mepc_data    (io_ctrl_out_mepc_data),
    .io_out_csr_we       (io_ctrl_out_csr_we)
  );
  assign io_ctrl_out_gpr_wd3 =
    io_in1_control_reg_w_data == 3'h3
      ? io_in1_csr_data_csr_rd
      : io_in1_control_reg_w_data == 3'h1
          ? io_in1_out_fu_alu
          : io_in1_control_reg_w_data == 3'h4
              ? io_in1_out_mem_out
              : io_in1_control_reg_w_data == 3'h2 ? io_in1_if_data_cur_pc_4 : 32'h0;	// src/main/scala/componets/WB/wb.scala:19:7, :57:69
  assign io_ctrl_out_gpr_we3 = io_in1_control_rg_we;	// src/main/scala/componets/WB/wb.scala:19:7
  assign io_ctrl_out_sys_code = io_in1_control_sys_code;	// src/main/scala/componets/WB/wb.scala:19:7
  assign io_ctrl_out_csr_wd = io_in1_out_fu_alu;	// src/main/scala/componets/WB/wb.scala:19:7
endmodule

